name: steelcontrol_mobile
description: Aplicativo móvel oficial do SteelControl integrado ao backend do TCC.
publish_to: "none"
version: 1.12.8+37

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  http_parser: ^4.1.2
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.3.2
  camera: ^0.12.0+2
  path_provider: ^2.1.4
  image_picker: ^1.1.2
  intl: ^0.19.0
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/steel-icon.svg
