import 'package:flutter/widgets.dart';

enum AppLanguage { pt, en, es, fr, de, it }

class AppStrings {
  AppStrings(this.language);

  final AppLanguage language;

  static const Map<String, List<String>> _values = {
    'appName': ['SteelControl', 'SteelControl', 'SteelControl', 'SteelControl', 'SteelControl', 'SteelControl'],
    'signIn': ['Entrar', 'Sign in', 'Iniciar sesión', 'Se connecter', 'Anmelden', 'Accedi'],
    'email': ['E-mail', 'Email', 'Correo', 'E-mail', 'E-Mail', 'E-mail'],
    'password': ['Senha', 'Password', 'Contraseña', 'Mot de passe', 'Passwort', 'Password'],
    'enterCompany': ['Acessar minha empresa', 'Access my company', 'Acceder a mi empresa', 'Accéder à mon entreprise', 'Auf mein Unternehmen zugreifen', 'Accedi alla mia azienda'],
    'faceSignIn': ['Entrar com reconhecimento facial', 'Sign in with face recognition', 'Entrar con reconocimiento facial', 'Connexion par reconnaissance faciale', 'Mit Gesichtserkennung anmelden', 'Accedi con riconoscimento facciale'],
    'machines': ['Máquinas', 'Machines', 'Máquinas', 'Machines', 'Maschinen', 'Macchine'],
    'overview': ['Visão geral', 'Overview', 'Resumen', 'Vue générale', 'Übersicht', 'Panoramica'],
    'production': ['Produção', 'Production', 'Producción', 'Production', 'Produktion', 'Produzione'],
    'maintenance': ['Manutenção', 'Maintenance', 'Mantenimiento', 'Maintenance', 'Wartung', 'Manutenzione'],
    'logs': ['Logs', 'Logs', 'Registros', 'Journaux', 'Protokolle', 'Registri'],
    'alerts': ['Alertas', 'Alerts', 'Alertas', 'Alertes', 'Warnungen', 'Avvisi'],
    'company': ['Minha empresa', 'My company', 'Mi empresa', 'Mon entreprise', 'Mein Unternehmen', 'La mia azienda'],
    'settings': ['Configurações', 'Settings', 'Configuración', 'Paramètres', 'Einstellungen', 'Impostazioni'],
    'logout': ['Sair', 'Sign out', 'Salir', 'Déconnexion', 'Abmelden', 'Esci'],
    'confirmLogoutTitle': ['Sair da conta?', 'Sign out?', '¿Salir de la cuenta?', 'Se déconnecter ?', 'Abmelden?', 'Uscire dall’account?'],
    'confirmLogoutMessage': ['Você tem certeza de que deseja encerrar esta sessão? Será necessário entrar novamente para acessar sua empresa.', 'Are you sure you want to end this session? You will need to sign in again to access your company.', '¿Está seguro de que desea cerrar esta sesión? Deberá iniciar sesión nuevamente para acceder a su empresa.', 'Voulez-vous vraiment fermer cette session ? Vous devrez vous reconnecter pour accéder à votre entreprise.', 'Möchten Sie diese Sitzung wirklich beenden? Sie müssen sich erneut anmelden, um auf Ihr Unternehmen zuzugreifen.', 'Vuoi davvero terminare questa sessione? Dovrai accedere di nuovo per entrare nella tua azienda.'],
    'confirmLogoutAction': ['Sair da conta', 'Sign out', 'Cerrar sesión', 'Se déconnecter', 'Abmelden', 'Esci dall’account'],
    'retry': ['Tentar novamente', 'Try again', 'Intentar de nuevo', 'Réessayer', 'Erneut versuchen', 'Riprova'],
    'noMachines': ['Nenhuma máquina cadastrada', 'No machines registered', 'No hay máquinas registradas', 'Aucune machine enregistrée', 'Keine Maschinen registriert', 'Nessuna macchina registrata'],
    'online': ['Online', 'Online', 'En línea', 'En ligne', 'Online', 'Online'],
    'offline': ['Offline', 'Offline', 'Sin conexión', 'Hors ligne', 'Offline', 'Offline'],
    'simulation': ['Simulação', 'Simulation', 'Simulación', 'Simulation', 'Simulation', 'Simulazione'],
    'real': ['Equipamento real', 'Real equipment', 'Equipo real', 'Équipement réel', 'Reale Anlage', 'Attrezzatura reale'],
    'temperature': ['Temperatura', 'Temperature', 'Temperatura', 'Température', 'Temperatur', 'Temperatura'],
    'energy': ['Carga elétrica', 'Electrical load', 'Carga eléctrica', 'Charge électrique', 'Elektrische Last', 'Carico elettrico'],
    'cycles': ['Ciclos', 'Cycles', 'Ciclos', 'Cycles', 'Zyklen', 'Cicli'],
    'status': ['Status', 'Status', 'Estado', 'État', 'Status', 'Stato'],
    'welcome': ['Bem-vindo', 'Welcome', 'Bienvenido', 'Bienvenue', 'Willkommen', 'Benvenuto'],
    'cancel': ['Cancelar', 'Cancel', 'Cancelar', 'Annuler', 'Abbrechen', 'Annulla'],
    'save': ['Salvar', 'Save', 'Guardar', 'Enregistrer', 'Speichern', 'Salva'],
    'edit': ['Editar', 'Edit', 'Editar', 'Modifier', 'Bearbeiten', 'Modifica'],
    'remove': ['Remover', 'Remove', 'Eliminar', 'Supprimer', 'Entfernen', 'Rimuovi'],
    'close': ['Fechar', 'Close', 'Cerrar', 'Fermer', 'Schließen', 'Chiudi'],
    'register': ['Registrar', 'Register', 'Registrar', 'Enregistrer', 'Registrieren', 'Registra'],
    'centralMachines': ['Central de máquinas', 'Machine center', 'Central de máquinas', 'Centre des machines', 'Maschinenzentrale', 'Centro macchine'],
    'selectEquipment': ['Selecione um equipamento para abrir seu painel exclusivo.', 'Select a machine to open its dedicated dashboard.', 'Seleccione un equipo para abrir su panel exclusivo.', 'Sélectionnez un équipement pour ouvrir son tableau de bord dédié.', 'Wählen Sie eine Maschine aus, um ihr eigenes Dashboard zu öffnen.', 'Seleziona un macchinario per aprire il relativo pannello.'],
    'selectedMachine': ['MÁQUINA SELECIONADA', 'SELECTED MACHINE', 'MÁQUINA SELECCIONADA', 'MACHINE SÉLECTIONNÉE', 'AUSGEWÄHLTE MASCHINE', 'MACCHINA SELEZIONATA'],
    'switchMachine': ['Trocar máquina', 'Switch machine', 'Cambiar máquina', 'Changer de machine', 'Maschine wechseln', 'Cambia macchina'],
    'preferencesTitle': ['Preferências do aplicativo', 'Application preferences', 'Preferencias de la aplicación', 'Préférences de l’application', 'Anwendungseinstellungen', 'Preferenze dell’applicazione'],
    'preferencesCaption': ['Personalize o tablet sem alterar os dados da operação.', 'Customize the tablet without changing operation data.', 'Personalice la tableta sin cambiar los datos operativos.', 'Personnalisez la tablette sans modifier les données d’exploitation.', 'Passen Sie das Tablet an, ohne Betriebsdaten zu ändern.', 'Personalizza il tablet senza modificare i dati operativi.'],
    'appearance': ['APARÊNCIA', 'APPEARANCE', 'APARIENCIA', 'APPARENCE', 'DARSTELLUNG', 'ASPETTO'],
    'systemTheme': ['Tema do sistema', 'System theme', 'Tema del sistema', 'Thème du système', 'Systemdesign', 'Tema del sistema'],
    'themeCaption': ['Escolha o modo mais confortável para o ambiente industrial.', 'Choose the most comfortable mode for the industrial environment.', 'Elija el modo más cómodo para el entorno industrial.', 'Choisissez le mode le plus confortable pour l’environnement industriel.', 'Wählen Sie den angenehmsten Modus für die Industrieumgebung.', 'Scegli la modalità più adatta all’ambiente industriale.'],
    'lightTheme': ['Tema claro', 'Light theme', 'Tema claro', 'Thème clair', 'Helles Design', 'Tema chiaro'],
    'darkTheme': ['Tema escuro', 'Dark theme', 'Tema oscuro', 'Thème sombre', 'Dunkles Design', 'Tema scuro'],
    'brightPlaces': ['Ambientes bem iluminados', 'Bright environments', 'Ambientes bien iluminados', 'Environnements lumineux', 'Helle Umgebungen', 'Ambienti luminosi'],
    'reduceBrightness': ['Reduz o brilho da tela', 'Reduces screen brightness', 'Reduce el brillo de la pantalla', 'Réduit la luminosité de l’écran', 'Reduziert die Bildschirmhelligkeit', 'Riduce la luminosità dello schermo'],
    'language': ['IDIOMA', 'LANGUAGE', 'IDIOMA', 'LANGUE', 'SPRACHE', 'LINGUA'],
    'interfaceLanguage': ['Linguagem da interface', 'Interface language', 'Idioma de la interfaz', 'Langue de l’interface', 'Sprache der Benutzeroberfläche', 'Lingua dell’interfaccia'],
    'languageSaved': ['A preferência fica salva neste dispositivo.', 'The preference is saved on this device.', 'La preferencia se guarda en este dispositivo.', 'La préférence est enregistrée sur cet appareil.', 'Die Einstellung wird auf diesem Gerät gespeichert.', 'La preferenza viene salvata su questo dispositivo.'],
    'endSession': ['Encerrar sessão', 'End session', 'Cerrar sesión', 'Fermer la session', 'Sitzung beenden', 'Termina sessione'],
    'endSessionCaption': ['Remove o acesso protegido somente deste dispositivo.', 'Removes protected access only from this device.', 'Elimina el acceso protegido solo de este dispositivo.', 'Supprime l’accès protégé uniquement de cet appareil.', 'Entfernt den geschützten Zugriff nur von diesem Gerät.', 'Rimuove l’accesso protetto solo da questo dispositivo.'],
    'organization': ['ORGANIZAÇÃO', 'ORGANIZATION', 'ORGANIZACIÓN', 'ORGANISATION', 'ORGANISATION', 'ORGANIZZAZIONE'],
    'manageCompany': ['Gerenciar minha empresa', 'Manage my company', 'Gestionar mi empresa', 'Gérer mon entreprise', 'Mein Unternehmen verwalten', 'Gestisci la mia azienda'],
    'activeCompany': ['Empresa ativa', 'Active company', 'Empresa activa', 'Entreprise active', 'Aktives Unternehmen', 'Azienda attiva'],
    'activeEmployees': ['Funcionários ativos', 'Active employees', 'Empleados activos', 'Employés actifs', 'Aktive Mitarbeiter', 'Dipendenti attivi'],
    'withBiometrics': ['Com biometria', 'With biometrics', 'Con biometría', 'Avec biométrie', 'Mit Biometrie', 'Con biometria'],
    'maintenanceCenter': ['Central de manutenção', 'Maintenance center', 'Central de mantenimiento', 'Centre de maintenance', 'Wartungszentrale', 'Centro manutenzione'],
    'maintenanceHistory': ['Histórico de manutenções', 'Maintenance history', 'Historial de mantenimiento', 'Historique des maintenances', 'Wartungsverlauf', 'Storico manutenzioni'],
    'maintenanceRegister': ['Registrar manutenção', 'Register maintenance', 'Registrar mantenimiento', 'Enregistrer une maintenance', 'Wartung erfassen', 'Registra manutenzione'],
    'maintenanceType': ['Tipo de manutenção', 'Maintenance type', 'Tipo de mantenimiento', 'Type de maintenance', 'Wartungsart', 'Tipo di manutenzione'],
    'responsibleTechnician': ['Técnico responsável', 'Responsible technician', 'Técnico responsable', 'Technicien responsable', 'Verantwortlicher Techniker', 'Tecnico responsabile'],
    'serviceDescription': ['Descrição do serviço', 'Service description', 'Descripción del servicio', 'Description du service', 'Leistungsbeschreibung', 'Descrizione del servizio'],
    'lastMaintenance': ['Última manutenção', 'Last maintenance', 'Último mantenimiento', 'Dernière maintenance', 'Letzte Wartung', 'Ultima manutenzione'],
    'nextMaintenance': ['Próxima manutenção', 'Next maintenance', 'Próximo mantenimiento', 'Prochaine maintenance', 'Nächste Wartung', 'Prossima manutenzione'],
    'situation': ['Situação', 'Situation', 'Situación', 'Situation', 'Situation', 'Situazione'],
    'noMaintenance': ['Nenhuma manutenção registrada para esta máquina.', 'No maintenance registered for this machine.', 'No hay mantenimiento registrado para esta máquina.', 'Aucune maintenance enregistrée pour cette machine.', 'Für diese Maschine wurde keine Wartung erfasst.', 'Nessuna manutenzione registrata per questa macchina.'],
    'maintenancePermission': ['Administradores, supervisores e técnicos podem registrar. Somente administradores podem excluir.', 'Administrators, supervisors and technicians can register. Only administrators can delete.', 'Administradores, supervisores y técnicos pueden registrar. Solo los administradores pueden eliminar.', 'Les administrateurs, superviseurs et techniciens peuvent enregistrer. Seuls les administrateurs peuvent supprimer.', 'Administratoren, Vorgesetzte und Techniker können Einträge erfassen. Nur Administratoren können löschen.', 'Amministratori, supervisori e tecnici possono registrare. Solo gli amministratori possono eliminare.'],
    'machineLogs': ['Logs da máquina', 'Machine logs', 'Registros de la máquina', 'Journaux de la machine', 'Maschinenprotokolle', 'Registri macchina'],
    'noLogs': ['Nenhum log registrado.', 'No logs registered.', 'No hay registros.', 'Aucun journal enregistré.', 'Keine Protokolle vorhanden.', 'Nessun registro presente.'],
    'adminOnly': ['Acesso exclusivo do administrador.', 'Administrator access only.', 'Acceso exclusivo del administrador.', 'Accès réservé à l’administrateur.', 'Zugriff nur für Administratoren.', 'Accesso riservato all’amministratore.'],
    'editCompany': ['Editar empresa', 'Edit company', 'Editar empresa', 'Modifier l’entreprise', 'Unternehmen bearbeiten', 'Modifica azienda'],
    'companyData': ['Dados da empresa', 'Company data', 'Datos de la empresa', 'Données de l’entreprise', 'Unternehmensdaten', 'Dati aziendali'],
    'institutionalInfo': ['Informações institucionais', 'Institutional information', 'Información institucional', 'Informations institutionnelles', 'Unternehmensinformationen', 'Informazioni aziendali'],
    'teamAccess': ['Equipe e acessos', 'Team and access', 'Equipo y accesos', 'Équipe et accès', 'Team und Zugriffe', 'Team e accessi'],
    'newEmployee': ['Novo funcionário', 'New employee', 'Nuevo empleado', 'Nouvel employé', 'Neuer Mitarbeiter', 'Nuovo dipendente'],
    'location': ['Localização', 'Location', 'Ubicación', 'Localisation', 'Standort', 'Posizione'],
    'notProvided': ['Não informado', 'Not provided', 'No informado', 'Non renseigné', 'Nicht angegeben', 'Non indicato'],
    'productionMachine': ['Produção da máquina', 'Machine production', 'Producción de la máquina', 'Production de la machine', 'Maschinenproduktion', 'Produzione macchina'],
    'operationTelemetry': ['Operação e telemetria', 'Operation and telemetry', 'Operación y telemetría', 'Opération et télémétrie', 'Betrieb und Telemetrie', 'Operazione e telemetria'],
    'operationTelemetryCaption': ['Leituras, conectividade e atividade enviadas pelo equipamento selecionado.', 'Readings, connectivity and activity sent by the selected equipment.', 'Lecturas, conectividad y actividad enviadas por el equipo seleccionado.', 'Mesures, connectivité et activité envoyées par l’équipement sélectionné.', 'Messwerte, Verbindung und Aktivität der ausgewählten Anlage.', 'Letture, connettività e attività inviate dall’apparecchiatura selezionata.'],
    'productionChart': ['Gráfico de produção', 'Production chart', 'Gráfico de producción', 'Graphique de production', 'Produktionsdiagramm', 'Grafico di produzione'],
    'productiveSummary': ['Resumo produtivo', 'Production summary', 'Resumen productivo', 'Résumé de production', 'Produktionsübersicht', 'Riepilogo produttivo'],
    'processesCounted': ['Processos contabilizados', 'Processes counted', 'Procesos contabilizados', 'Processus comptabilisés', 'Erfasste Prozesse', 'Processi contabilizzati'],
    'cyclesReported': ['Ciclos informados', 'Cycles reported', 'Ciclos informados', 'Cycles signalés', 'Gemeldete Zyklen', 'Cicli segnalati'],
    'signalQuality': ['Qualidade do sinal', 'Signal quality', 'Calidad de señal', 'Qualité du signal', 'Signalqualität', 'Qualità del segnale'],
    'controllerIndicator': ['Indicador do controlador', 'Controller indicator', 'Indicador del controlador', 'Indicateur du contrôleur', 'Controlleranzeige', 'Indicatore del controller'],
    'compatibleModules': ['Módulos operacionais compatíveis', 'Compatible operating modules', 'Módulos operativos compatibles', 'Modules opérationnels compatibles', 'Kompatible Betriebsmodule', 'Moduli operativi compatibili'],
    'lastReading': ['Última leitura', 'Last reading', 'Última lectura', 'Dernière mesure', 'Letzte Messung', 'Ultima lettura'],
    'productionPeak': ['Pico de produção', 'Production peak', 'Pico de producción', 'Pic de production', 'Produktionsspitze', 'Picco di produzione'],
    'productionAverage': ['Média do período', 'Period average', 'Promedio del período', 'Moyenne de la période', 'Periodendurchschnitt', 'Media del periodo'],
    'noTelemetry': ['Nenhuma telemetria recebida desta máquina.', 'No telemetry received from this machine.', 'No se recibió telemetría de esta máquina.', 'Aucune télémétrie reçue de cette machine.', 'Keine Telemetrie von dieser Maschine empfangen.', 'Nessuna telemetria ricevuta da questa macchina.'],
    'notConfigured': ['Não configurado', 'Not configured', 'No configurado', 'Non configuré', 'Nicht konfiguriert', 'Non configurato'],
    'telemetryHistory': ['Histórico de telemetria', 'Telemetry history', 'Historial de telemetría', 'Historique de télémétrie', 'Telemetrieverlauf', 'Storico telemetria'],
    'waitingReadings': ['Aguardando leituras da máquina.', 'Waiting for machine readings.', 'Esperando lecturas de la máquina.', 'En attente des mesures de la machine.', 'Warten auf Maschinenmesswerte.', 'In attesa delle letture della macchina.'],
    'recentRecord': ['Registro mais recente', 'Most recent record', 'Registro más reciente', 'Enregistrement le plus récent', 'Neuester Eintrag', 'Registrazione più recente'],
    'preventiveForecast': ['Previsão preventiva', 'Preventive forecast', 'Previsión preventiva', 'Prévision préventive', 'Präventive Planung', 'Previsione preventiva'],
    'reviewBasis': ['Base para revisão', 'Review basis', 'Base para revisión', 'Base de révision', 'Prüfgrundlage', 'Base per la revisione'],
    'maintenanceSuccess': ['Manutenção registrada com sucesso.', 'Maintenance registered successfully.', 'Mantenimiento registrado correctamente.', 'Maintenance enregistrée avec succès.', 'Wartung erfolgreich erfasst.', 'Manutenzione registrata correttamente.'],
    'recordsOnly': ['Registros gerados somente por esta máquina.', 'Records generated only by this machine.', 'Registros generados solo por esta máquina.', 'Enregistrements générés uniquement par cette machine.', 'Nur von dieser Maschine erzeugte Einträge.', 'Registri generati solo da questa macchina.'],
    'machineAlerts': ['Alertas da máquina', 'Machine alerts', 'Alertas de la máquina', 'Alertes de la machine', 'Maschinenwarnungen', 'Avvisi macchina'],
    'noAlerts': ['Nenhum alerta ativo.', 'No active alerts.', 'No hay alertas activas.', 'Aucune alerte active.', 'Keine aktiven Warnungen.', 'Nessun avviso attivo.'],
    'eventsOnly': ['Ocorrências exclusivas desta máquina.', 'Events exclusive to this machine.', 'Eventos exclusivos de esta máquina.', 'Événements propres à cette machine.', 'Ereignisse ausschließlich dieser Maschine.', 'Eventi esclusivi di questa macchina.'],
    'machineDiagnostics': ['Diagnóstico da máquina', 'Machine diagnostics', 'Diagnóstico de la máquina', 'Diagnostic de la machine', 'Maschinendiagnose', 'Diagnostica macchina'],
    'machineIndicators': ['Indicadores vinculados exclusivamente ao equipamento selecionado.', 'Indicators linked exclusively to the selected equipment.', 'Indicadores vinculados exclusivamente al equipo seleccionado.', 'Indicateurs liés exclusivement à l’équipement sélectionné.', 'Anzeigen ausschließlich für die ausgewählte Maschine.', 'Indicatori collegati esclusivamente al macchinario selezionato.'],
    'vibration': ['Vibração', 'Vibration', 'Vibración', 'Vibration', 'Vibration', 'Vibrazione'],
    'current': ['Corrente', 'Current', 'Corriente', 'Courant', 'Strom', 'Corrente'],
    'mode': ['Modo', 'Mode', 'Modo', 'Mode', 'Modus', 'Modalità'],
    'demoMode': ['Modo demonstração', 'Demonstration mode', 'Modo demostración', 'Mode démonstration', 'Demonstrationsmodus', 'Modalità dimostrazione'],
    'demoCaption': ['Cenários seguros para apresentar o TCC sem equipamento físico.', 'Safe scenarios for presenting the project without physical equipment.', 'Escenarios seguros para presentar el proyecto sin equipo físico.', 'Scénarios sûrs pour présenter le projet sans équipement physique.', 'Sichere Szenarien zur Präsentation ohne physische Anlage.', 'Scenari sicuri per presentare il progetto senza apparecchiatura fisica.'],
    'totalProduction': ['Produção total', 'Total production', 'Producción total', 'Production totale', 'Gesamtproduktion', 'Produzione totale'],
    'executedCycles': ['Ciclos executados', 'Executed cycles', 'Ciclos ejecutados', 'Cycles exécutés', 'Ausgeführte Zyklen', 'Cicli eseguiti'],
    'averageLoad': ['Carga média', 'Average load', 'Carga media', 'Charge moyenne', 'Durchschnittslast', 'Carico medio'],
    'platform': ['PLATAFORMA DE GESTÃO INDUSTRIAL', 'INDUSTRIAL MANAGEMENT PLATFORM', 'PLATAFORMA DE GESTIÓN INDUSTRIAL', 'PLATEFORME DE GESTION INDUSTRIELLE', 'INDUSTRIELLE MANAGEMENTPLATTFORM', 'PIATTAFORMA DI GESTIONE INDUSTRIALE'],
    'accessCompany': ['Acesse sua empresa', 'Access your company', 'Acceda a su empresa', 'Accédez à votre entreprise', 'Auf Ihr Unternehmen zugreifen', 'Accedi alla tua azienda'],
    'loginCaption': ['Entre com seu e-mail corporativo e acompanhe sua operação pelo tablet.', 'Sign in with your corporate email and monitor your operation from the tablet.', 'Ingrese con su correo corporativo y supervise la operación desde la tableta.', 'Connectez-vous avec votre e-mail professionnel et suivez l’exploitation sur la tablette.', 'Melden Sie sich mit Ihrer Firmen-E-Mail an und überwachen Sie den Betrieb über das Tablet.', 'Accedi con l’e-mail aziendale e monitora le operazioni dal tablet.'],
    'newCompany': ['NOVA EMPRESA', 'NEW COMPANY', 'NUEVA EMPRESA', 'NOUVELLE ENTREPRISE', 'NEUES UNTERNEHMEN', 'NUOVA AZIENDA'],
    'registerCompany': ['Cadastrar minha empresa', 'Register my company', 'Registrar mi empresa', 'Enregistrer mon entreprise', 'Mein Unternehmen registrieren', 'Registra la mia azienda'],
    'heroTitle': ['Sua operação industrial\nna palma da mão.', 'Your industrial operation\nin the palm of your hand.', 'Su operación industrial\nen la palma de su mano.', 'Votre exploitation industrielle\nau creux de la main.', 'Ihr Industriebetrieb\nin Ihrer Hand.', 'La tua attività industriale\nnel palmo della mano.'],
    'heroCaption': ['Máquinas, produção, manutenção, alertas e segurança sincronizados com o mesmo SteelControl do desktop.', 'Machines, production, maintenance, alerts and safety synchronized with the desktop SteelControl.', 'Máquinas, producción, mantenimiento, alertas y seguridad sincronizados con SteelControl de escritorio.', 'Machines, production, maintenance, alertes et sécurité synchronisées avec SteelControl sur ordinateur.', 'Maschinen, Produktion, Wartung, Warnungen und Sicherheit mit SteelControl Desktop synchronisiert.', 'Macchine, produzione, manutenzione, avvisi e sicurezza sincronizzati con SteelControl desktop.'],
    'protectedAccess': ['Acesso protegido e dados centralizados', 'Protected access and centralized data', 'Acceso protegido y datos centralizados', 'Accès protégé et données centralisées', 'Geschützter Zugriff und zentrale Daten', 'Accesso protetto e dati centralizzati'],
    'preferences': ['Preferências', 'Preferences', 'Preferencias', 'Préférences', 'Einstellungen', 'Preferenze'],
    'adjustExperience': ['Ajuste a experiência neste dispositivo.', 'Adjust the experience on this device.', 'Ajuste la experiencia en este dispositivo.', 'Ajustez l’expérience sur cet appareil.', 'Passen Sie die Nutzung auf diesem Gerät an.', 'Personalizza l’esperienza su questo dispositivo.'],
    'themeApplied': ['Tema aplicado em todo o aplicativo', 'Theme applied throughout the application', 'Tema aplicado en toda la aplicación', 'Thème appliqué dans toute l’application', 'Design in der gesamten Anwendung', 'Tema applicato a tutta l’applicazione'],
    'finish': ['Concluir', 'Finish', 'Finalizar', 'Terminer', 'Fertig', 'Concludi'],
    'faceRegister': ['Cadastrar facial', 'Register face', 'Registrar rostro', 'Enregistrer le visage', 'Gesicht registrieren', 'Registra volto'],
    'automaticValidation': ['Validação automática em andamento...', 'Automatic validation in progress...', 'Validación automática en curso...', 'Validation automatique en cours...', 'Automatische Prüfung läuft...', 'Validazione automatica in corso...'],
    'imagesAuthOnly': ['As imagens são usadas somente durante a autenticação.', 'Images are used only during authentication.', 'Las imágenes se utilizan solo durante la autenticación.', 'Les images sont utilisées uniquement pendant l’authentification.', 'Bilder werden nur während der Authentifizierung verwendet.', 'Le immagini vengono usate solo durante l’autenticazione.'],
    'cameraPreparing': ['Preparando a câmera', 'Preparing camera', 'Preparando la cámara', 'Préparation de la caméra', 'Kamera wird vorbereitet', 'Preparazione della fotocamera'],
    'eyesHeight': ['Mantenha o tablet na altura dos olhos.', 'Keep the tablet at eye level.', 'Mantenga la tableta a la altura de los ojos.', 'Gardez la tablette à hauteur des yeux.', 'Halten Sie das Tablet auf Augenhöhe.', 'Tieni il tablet all’altezza degli occhi.'],
    'biometricRegister': ['Cadastrar biometria', 'Register biometrics', 'Registrar biometría', 'Enregistrer la biométrie', 'Biometrie registrieren', 'Registra biometria'],
    'faceRecognition': ['Reconhecimento facial', 'Face recognition', 'Reconocimiento facial', 'Reconnaissance faciale', 'Gesichtserkennung', 'Riconoscimento facciale'],
    'centerFace': ['Centralize o rosto. A captura começará automaticamente.', 'Center your face. Capture will start automatically.', 'Centre el rostro. La captura comenzará automáticamente.', 'Centrez votre visage. La capture démarrera automatiquement.', 'Zentrieren Sie Ihr Gesicht. Die Aufnahme startet automatisch.', 'Centra il viso. L’acquisizione inizierà automaticamente.'],
    'lookCamera': ['Olhe diretamente para a câmera', 'Look directly at the camera', 'Mire directamente a la cámara', 'Regardez directement la caméra', 'Schauen Sie direkt in die Kamera', 'Guarda direttamente la fotocamera'],
    'stayCentered': ['Mantenha o rosto centralizado e imóvel.', 'Keep your face centered and still.', 'Mantenga el rostro centrado e inmóvil.', 'Gardez le visage centré et immobile.', 'Halten Sie Ihr Gesicht zentriert und ruhig.', 'Mantieni il viso centrato e fermo.'],
    'liveness': ['Prova de vida', 'Liveness check', 'Prueba de vida', 'Détection de vivacité', 'Lebenderkennung', 'Verifica di vitalità'],
    'turnHead': ['Vire levemente a cabeça para um dos lados.', 'Turn your head slightly to one side.', 'Gire ligeramente la cabeza hacia un lado.', 'Tournez légèrement la tête d’un côté.', 'Drehen Sie den Kopf leicht zur Seite.', 'Gira leggermente la testa di lato.'],
    'identityConfirmed': ['Identidade confirmada', 'Identity confirmed', 'Identidad confirmada', 'Identité confirmée', 'Identität bestätigt', 'Identità confermata'],
    'protectedIdentity': ['IDENTIDADE PROTEGIDA', 'IDENTITY PROTECTED', 'IDENTIDAD PROTEGIDA', 'IDENTITÉ PROTÉGÉE', 'IDENTITÄT GESCHÜTZT', 'IDENTITÀ PROTETTA'],
    'positionFace': ['POSICIONE O ROSTO NA ÁREA INDICADA', 'POSITION YOUR FACE IN THE INDICATED AREA', 'COLOQUE EL ROSTRO EN EL ÁREA INDICADA', 'PLACEZ VOTRE VISAGE DANS LA ZONE INDIQUÉE', 'POSITIONIEREN SIE IHR GESICHT IM MARKIERTEN BEREICH', 'POSIZIONA IL VISO NELL’AREA INDICATA'],
    'industrialEquipment': ['EQUIPAMENTOS INDUSTRIAIS', 'INDUSTRIAL EQUIPMENT', 'EQUIPOS INDUSTRIALES', 'ÉQUIPEMENTS INDUSTRIELS', 'INDUSTRIEANLAGEN', 'APPARECCHIATURE INDUSTRIALI'],
    'registeredMachines': ['máquinas cadastradas', 'registered machines', 'máquinas registradas', 'machines enregistrées', 'registrierte Maschinen', 'macchine registrate'],
    'machinesCaption': ['Cadastre, configure e acompanhe os mesmos equipamentos do desktop.', 'Register, configure and monitor the same equipment as on the desktop.', 'Registre, configure y supervise los mismos equipos del escritorio.', 'Enregistrez, configurez et suivez les mêmes équipements que sur ordinateur.', 'Registrieren, konfigurieren und überwachen Sie dieselben Anlagen wie am Desktop.', 'Registra, configura e monitora le stesse apparecchiature del desktop.'],
    'companyEquipmentTitle': ['Equipamentos da sua empresa', 'Your company equipment', 'Equipos de su empresa', 'Équipements de votre entreprise', 'Anlagen Ihres Unternehmens', 'Apparecchiature della tua azienda'],
    'companyEquipmentCaption': ['Cadastre máquinas, robôs industriais e outros equipamentos da sua operação. O SteelControl organiza temperatura, produção, ciclos, energia, manutenção e alertas.', 'Register machines, industrial robots and other operational equipment. SteelControl organizes temperature, production, cycles, energy, maintenance and alerts.', 'Registre máquinas, robots industriales y otros equipos. SteelControl organiza temperatura, producción, ciclos, energía, mantenimiento y alertas.', 'Enregistrez des machines, robots industriels et autres équipements. SteelControl organise température, production, cycles, énergie, maintenance et alertes.', 'Registrieren Sie Maschinen, Industrieroboter und weitere Anlagen. SteelControl organisiert Temperatur, Produktion, Zyklen, Energie, Wartung und Warnungen.', 'Registra macchine, robot industriali e altre apparecchiature. SteelControl organizza temperatura, produzione, cicli, energia, manutenzione e avvisi.'],
    'centralizedMonitoring': ['Monitoramento centralizado', 'Centralized monitoring', 'Monitoreo centralizado', 'Surveillance centralisée', 'Zentrale Überwachung', 'Monitoraggio centralizzato'],
    'operationalHistory': ['Histórico operacional', 'Operational history', 'Historial operativo', 'Historique opérationnel', 'Betriebsverlauf', 'Storico operativo'],
    'integratedMaintenance': ['Manutenção integrada', 'Integrated maintenance', 'Mantenimiento integrado', 'Maintenance intégrée', 'Integrierte Wartung', 'Manutenzione integrata'],
    'equipmentCount': ['Equipamentos', 'Equipment', 'Equipos', 'Équipements', 'Anlagen', 'Apparecchiature'],
    'inOperation': ['Em operação', 'In operation', 'En operación', 'En fonctionnement', 'In Betrieb', 'In funzione'],
    'underMaintenance': ['Em manutenção', 'Under maintenance', 'En mantenimiento', 'En maintenance', 'In Wartung', 'In manutenzione'],
    'withAlert': ['Com alerta', 'With alert', 'Con alerta', 'Avec alerte', 'Mit Warnung', 'Con avviso'],
    'equipmentManagement': ['GESTÃO DE EQUIPAMENTOS', 'EQUIPMENT MANAGEMENT', 'GESTIÓN DE EQUIPOS', 'GESTION DES ÉQUIPEMENTS', 'ANLAGENVERWALTUNG', 'GESTIONE APPARECCHIATURE'],
    'registerEquipmentTitle': ['Cadastrar novo equipamento', 'Register new equipment', 'Registrar nuevo equipo', 'Enregistrer un nouvel équipement', 'Neue Anlage registrieren', 'Registra nuova apparecchiatura'],
    'registerEquipmentCaption': ['Cadastre a identificação e prepare a comunicação para integração com o equipamento real.', 'Register its identity and prepare communication for real equipment integration.', 'Registre la identificación y prepare la comunicación con el equipo real.', 'Enregistrez son identité et préparez la communication avec l’équipement réel.', 'Erfassen Sie die Identität und bereiten Sie die Kommunikation mit der realen Anlage vor.', 'Registra l’identità e prepara la comunicazione con l’apparecchiatura reale.'],
    'industrialPark': ['PARQUE INDUSTRIAL', 'INDUSTRIAL PARK', 'PARQUE INDUSTRIAL', 'PARC INDUSTRIEL', 'INDUSTRIEPARK', 'PARCO INDUSTRIALE'],
    'registeredEquipmentTitle': ['Equipamentos cadastrados', 'Registered equipment', 'Equipos registrados', 'Équipements enregistrés', 'Registrierte Anlagen', 'Apparecchiature registrate'],
    'searchEquipment': ['Buscar equipamento...', 'Search equipment...', 'Buscar equipo...', 'Rechercher un équipement...', 'Anlage suchen...', 'Cerca apparecchiatura...'],
    'allTypes': ['Todos os tipos', 'All types', 'Todos los tipos', 'Tous les types', 'Alle Typen', 'Tutti i tipi'],
    'allStatuses': ['Todos os status', 'All statuses', 'Todos los estados', 'Tous les statuts', 'Alle Status', 'Tutti gli stati'],
    'noFilterResults': ['Nenhum equipamento corresponde aos filtros.', 'No equipment matches the filters.', 'Ningún equipo coincide con los filtros.', 'Aucun équipement ne correspond aux filtres.', 'Keine Anlage entspricht den Filtern.', 'Nessuna apparecchiatura corrisponde ai filtri.'],
    'welcomeBackName': ['Bem-vindo, {name}!', 'Welcome, {name}!', '¡Bienvenido, {name}!', 'Bienvenue, {name} !', 'Willkommen, {name}!', 'Benvenuto, {name}!'],
    'welcomeCreatedName': ['Bem-vindo ao SteelControl, {name}!', 'Welcome to SteelControl, {name}!', '¡Bienvenido a SteelControl, {name}!', 'Bienvenue sur SteelControl, {name} !', 'Willkommen bei SteelControl, {name}!', 'Benvenuto in SteelControl, {name}!'],
    'loginSuccessCaption': ['Acesso confirmado. Estamos preparando o painel da sua empresa com segurança.', 'Access confirmed. We are securely preparing your company dashboard.', 'Acceso confirmado. Estamos preparando de forma segura el panel de su empresa.', 'Accès confirmé. Nous préparons le tableau de bord de votre entreprise en toute sécurité.', 'Zugriff bestätigt. Das Dashboard Ihres Unternehmens wird sicher vorbereitet.', 'Accesso confermato. Stiamo preparando in sicurezza il pannello della tua azienda.'],
    'registerSuccessCaption': ['Sua empresa foi criada e sua conta administrativa está pronta com segurança.', 'Your company has been created and your administrator account is securely ready.', 'Su empresa fue creada y su cuenta administrativa está lista de forma segura.', 'Votre entreprise a été créée et votre compte administrateur est prêt en toute sécurité.', 'Ihr Unternehmen wurde erstellt und Ihr Administratorkonto ist sicher einsatzbereit.', 'La tua azienda è stata creata e il tuo account amministratore è pronto in sicurezza.'],
    'openingWorkspace': ['Abrindo seu ambiente industrial...', 'Opening your industrial workspace...', 'Abriendo su entorno industrial...', 'Ouverture de votre environnement industriel...', 'Ihr industrieller Arbeitsbereich wird geöffnet...', 'Apertura del tuo ambiente industriale...'],
    'newMachine': ['Nova máquina', 'New machine', 'Nueva máquina', 'Nouvelle machine', 'Neue Maschine', 'Nuova macchina'],
    'noMachinesCompany': ['Nenhuma máquina cadastrada nesta empresa.', 'No machines registered for this company.', 'No hay máquinas registradas en esta empresa.', 'Aucune machine enregistrée pour cette entreprise.', 'Für dieses Unternehmen sind keine Maschinen registriert.', 'Nessuna macchina registrata per questa azienda.'],
    'firstMachine': ['Cadastrar primeira máquina', 'Register first machine', 'Registrar primera máquina', 'Enregistrer la première machine', 'Erste Maschine registrieren', 'Registra la prima macchina'],
    'openPanel': ['Abrir painel', 'Open dashboard', 'Abrir panel', 'Ouvrir le tableau de bord', 'Dashboard öffnen', 'Apri pannello'],
    'openDobotPanel': ['Abrir painel Dobot', 'Open Dobot dashboard', 'Abrir panel Dobot', 'Ouvrir le tableau de bord Dobot', 'Dobot-Dashboard öffnen', 'Apri pannello Dobot'],
    'accessConfirmed': ['Acesso confirmado', 'Access confirmed', 'Acceso confirmado', 'Accès confirmé', 'Zugriff bestätigt', 'Accesso confermato'],
    'secureEnvironment': ['AMBIENTE INDUSTRIAL SEGURO', 'SECURE INDUSTRIAL ENVIRONMENT', 'ENTORNO INDUSTRIAL SEGURO', 'ENVIRONNEMENT INDUSTRIEL SÉCURISÉ', 'SICHERE INDUSTRIEUMGEBUNG', 'AMBIENTE INDUSTRIALE SICURO'],
    'protectedSession': ['Sessão protegida', 'Protected session', 'Sesión protegida', 'Session protégée', 'Geschützte Sitzung', 'Sessione protetta'],
    'syncedData': ['Dados sincronizados', 'Synchronized data', 'Datos sincronizados', 'Données synchronisées', 'Synchronisierte Daten', 'Dati sincronizzati'],
    'goDashboard': ['Ir para o painel', 'Go to dashboard', 'Ir al panel', 'Accéder au tableau de bord', 'Zum Dashboard', 'Vai al pannello'],
    'industrialManagement': ['GESTÃO INDUSTRIAL', 'INDUSTRIAL MANAGEMENT', 'GESTIÓN INDUSTRIAL', 'GESTION INDUSTRIELLE', 'INDUSTRIEMANAGEMENT', 'GESTIONE INDUSTRIALE'],
    'themeAndLanguage': ['Tema e idioma', 'Theme and language', 'Tema e idioma', 'Thème et langue', 'Design und Sprache', 'Tema e lingua'],
    'validEmail': ['Informe um e-mail válido.', 'Enter a valid email address.', 'Ingrese un correo válido.', 'Saisissez une adresse e-mail valide.', 'Geben Sie eine gültige E-Mail-Adresse ein.', 'Inserisci un indirizzo e-mail valido.'],
    'requiredField': ['Campo obrigatório.', 'Required field.', 'Campo obligatorio.', 'Champ obligatoire.', 'Pflichtfeld.', 'Campo obbligatorio.'],
    'minimumPassword': ['Use pelo menos 8 caracteres.', 'Use at least 8 characters.', 'Use al menos 8 caracteres.', 'Utilisez au moins 8 caractères.', 'Verwenden Sie mindestens 8 Zeichen.', 'Usa almeno 8 caratteri.'],
    'registerCompanyTitle': ['Cadastrar empresa', 'Register company', 'Registrar empresa', 'Enregistrer une entreprise', 'Unternehmen registrieren', 'Registra azienda'],
    'startSteelControl': ['Comece no SteelControl', 'Get started with SteelControl', 'Comience con SteelControl', 'Commencez avec SteelControl', 'Mit SteelControl starten', 'Inizia con SteelControl'],
    'createCompanyWorkspace': ['Crie o ambiente da sua empresa', 'Create your company workspace', 'Cree el entorno de su empresa', 'Créez l’espace de votre entreprise', 'Arbeitsbereich Ihres Unternehmens erstellen', 'Crea l’ambiente della tua azienda'],
    'registrationIntro': ['Depois da confirmação do e-mail, o sistema cria a empresa e solicita a biometria facial do administrador para concluir o primeiro acesso.', 'After email confirmation, the system creates the company and requests the administrator’s facial biometrics to complete first access.', 'Después de confirmar el correo, el sistema crea la empresa y solicita la biometría facial del administrador para completar el primer acceso.', 'Après confirmation de l’e-mail, le système crée l’entreprise et demande la biométrie faciale de l’administrateur pour terminer le premier accès.', 'Nach Bestätigung der E-Mail erstellt das System das Unternehmen und fordert die Gesichtsbiometrie des Administrators für den ersten Zugriff an.', 'Dopo la conferma dell’e-mail, il sistema crea l’azienda e richiede la biometria facciale dell’amministratore per completare il primo accesso.'],
    'companyName': ['Nome da empresa', 'Company name', 'Nombre de la empresa', 'Nom de l’entreprise', 'Unternehmensname', 'Nome azienda'],
    'administrator': ['Administrador', 'Administrator', 'Administrador', 'Administrateur', 'Administrator', 'Amministratore'],
    'fullName': ['Nome completo', 'Full name', 'Nombre completo', 'Nom complet', 'Vollständiger Name', 'Nome completo'],
    'corporateEmail': ['E-mail corporativo', 'Corporate email', 'Correo corporativo', 'E-mail professionnel', 'Firmen-E-Mail', 'E-mail aziendale'],
    'emailConfirmation': ['Confirmação do e-mail', 'Email confirmation', 'Confirmación del correo', 'Confirmation de l’e-mail', 'E-Mail-Bestätigung', 'Conferma e-mail'],
    'sixDigitCode': ['Código de 6 dígitos', '6-digit code', 'Código de 6 dígitos', 'Code à 6 chiffres', '6-stelliger Code', 'Codice a 6 cifre'],
    'codeSent': ['Código enviado para seu e-mail.', 'Code sent to your email.', 'Código enviado a su correo.', 'Code envoyé à votre e-mail.', 'Code an Ihre E-Mail gesendet.', 'Codice inviato alla tua e-mail.'],
    'enterSixDigitCode': ['Digite o código de 6 dígitos.', 'Enter the 6-digit code.', 'Ingrese el código de 6 dígitos.', 'Saisissez le code à 6 chiffres.', 'Geben Sie den 6-stelligen Code ein.', 'Inserisci il codice a 6 cifre.'],
    'confirmAndRegisterFace': ['Confirmar e cadastrar facial', 'Confirm and register face', 'Confirmar y registrar rostro', 'Confirmer et enregistrer le visage', 'Bestätigen und Gesicht registrieren', 'Conferma e registra il volto'],
    'verifyEmailContinue': ['Verificar e-mail e continuar', 'Verify email and continue', 'Verificar correo y continuar', 'Vérifier l’e-mail et continuer', 'E-Mail prüfen und fortfahren', 'Verifica e-mail e continua'],
    'changeData': ['Alterar dados', 'Change details', 'Cambiar datos', 'Modifier les données', 'Daten ändern', 'Modifica dati'],
    'companyTeamCaption': ['Equipe, acessos e identidade institucional.', 'Team, access and institutional identity.', 'Equipo, accesos e identidad institucional.', 'Équipe, accès et identité institutionnelle.', 'Team, Zugriffe und Unternehmensidentität.', 'Team, accessi e identità aziendale.'],
    'phone': ['Telefone', 'Phone', 'Teléfono', 'Téléphone', 'Telefon', 'Telefono'],
    'website': ['Site', 'Website', 'Sitio web', 'Site web', 'Webseite', 'Sito web'],
    'recentAudit': ['Auditoria recente', 'Recent audit', 'Auditoría reciente', 'Audit récent', 'Letzte Prüfung', 'Audit recente'],
    'you': ['VOCÊ', 'YOU', 'TÚ', 'VOUS', 'SIE', 'TU'],
    'activeBiometrics': ['BIOMETRIA ATIVA', 'BIOMETRICS ACTIVE', 'BIOMETRÍA ACTIVA', 'BIOMÉTRIE ACTIVE', 'BIOMETRIE AKTIV', 'BIOMETRIA ATTIVA'],
    'noBiometrics': ['SEM BIOMETRIA', 'NO BIOMETRICS', 'SIN BIOMETRÍA', 'SANS BIOMÉTRIE', 'KEINE BIOMETRIE', 'SENZA BIOMETRIA'],
    'manageEmployee': ['Gerenciar funcionário', 'Manage employee', 'Gestionar empleado', 'Gérer l’employé', 'Mitarbeiter verwalten', 'Gestisci dipendente'],
    'editLoginRole': ['Editar login e cargo', 'Edit login and role', 'Editar acceso y cargo', 'Modifier l’accès et le rôle', 'Anmeldung und Rolle bearbeiten', 'Modifica accesso e ruolo'],
    'manageFace': ['Gerenciar facial', 'Manage face', 'Gestionar rostro', 'Gérer le visage', 'Gesicht verwalten', 'Gestisci volto'],
    'dismissEmployee': ['Demitir funcionário', 'Dismiss employee', 'Despedir empleado', 'Licencier l’employé', 'Mitarbeiter entlassen', 'Licenzia dipendente'],
    'editAccess': ['Editar acesso', 'Edit access', 'Editar acceso', 'Modifier l’accès', 'Zugriff bearbeiten', 'Modifica accesso'],
    'registerEmployee': ['Cadastrar funcionário', 'Register employee', 'Registrar empleado', 'Enregistrer un employé', 'Mitarbeiter registrieren', 'Registra dipendente'],
    'accessEmail': ['E-mail de acesso', 'Access email', 'Correo de acceso', 'E-mail d’accès', 'Zugangs-E-Mail', 'E-mail di accesso'],
    'role': ['Cargo', 'Role', 'Cargo', 'Rôle', 'Rolle', 'Ruolo'],
    'newPasswordOptional': ['Nova senha (opcional)', 'New password (optional)', 'Nueva contraseña (opcional)', 'Nouveau mot de passe (facultatif)', 'Neues Passwort (optional)', 'Nuova password (opzionale)'],
    'initialPassword': ['Senha inicial', 'Initial password', 'Contraseña inicial', 'Mot de passe initial', 'Anfangspasswort', 'Password iniziale'],
    'saveChanges': ['Salvar alterações', 'Save changes', 'Guardar cambios', 'Enregistrer les modifications', 'Änderungen speichern', 'Salva modifiche'],
    'confirm': ['Confirmar', 'Confirm', 'Confirmar', 'Confirmer', 'Bestätigen', 'Conferma'],
    'confirmNewEmail': ['Confirme o novo e-mail', 'Confirm the new email', 'Confirme el nuevo correo', 'Confirmez le nouvel e-mail', 'Neue E-Mail bestätigen', 'Conferma la nuova e-mail'],
    'address': ['Endereço', 'Address', 'Dirección', 'Adresse', 'Adresse', 'Indirizzo'],
    'number': ['Número', 'Number', 'Número', 'Numéro', 'Nummer', 'Numero'],
    'district': ['Bairro', 'District', 'Barrio', 'Quartier', 'Stadtteil', 'Quartiere'],
    'city': ['Cidade', 'City', 'Ciudad', 'Ville', 'Stadt', 'Città'],
    'state': ['Estado', 'State', 'Estado', 'État', 'Bundesland', 'Provincia'],
    'zipCode': ['CEP', 'Postal code', 'Código postal', 'Code postal', 'Postleitzahl', 'CAP'],
    'country': ['País', 'Country', 'País', 'Pays', 'Land', 'Paese'],
    'editEquipment': ['Editar equipamento', 'Edit equipment', 'Editar equipo', 'Modifier l’équipement', 'Anlage bearbeiten', 'Modifica apparecchiatura'],
    'registerEquipment': ['Cadastrar equipamento', 'Register equipment', 'Registrar equipo', 'Enregistrer l’équipement', 'Anlage registrieren', 'Registra apparecchiatura'],
    'machineName': ['Nome da máquina', 'Machine name', 'Nombre de la máquina', 'Nom de la machine', 'Maschinenname', 'Nome macchina'],
    'sector': ['Setor', 'Sector', 'Sector', 'Secteur', 'Bereich', 'Settore'],
    'model': ['Modelo', 'Model', 'Modelo', 'Modèle', 'Modell', 'Modello'],
    'internalCode': ['Código interno', 'Internal code', 'Código interno', 'Code interne', 'Interner Code', 'Codice interno'],
    'equipmentType': ['Tipo do equipamento', 'Equipment type', 'Tipo de equipo', 'Type d’équipement', 'Anlagentyp', 'Tipo di apparecchiatura'],
    'manufacturer': ['Fabricante', 'Manufacturer', 'Fabricante', 'Fabricant', 'Hersteller', 'Produttore'],
    'operationalDescription': ['Descrição operacional', 'Operational description', 'Descripción operativa', 'Description opérationnelle', 'Betriebsbeschreibung', 'Descrizione operativa'],
    'operationMode': ['Modo de operação', 'Operating mode', 'Modo de operación', 'Mode de fonctionnement', 'Betriebsart', 'Modalità operativa'],
    'industrialCommunication': ['Comunicação industrial', 'Industrial communication', 'Comunicación industrial', 'Communication industrielle', 'Industriekommunikation', 'Comunicazione industriale'],
    'controllerGateway': ['Controlador / gateway', 'Controller / gateway', 'Controlador / gateway', 'Contrôleur / passerelle', 'Controller / Gateway', 'Controller / gateway'],
    'protocol': ['Protocolo', 'Protocol', 'Protocolo', 'Protocole', 'Protokoll', 'Protocollo'],
    'configureLater': ['Configurar depois', 'Configure later', 'Configurar después', 'Configurer plus tard', 'Später konfigurieren', 'Configura dopo'],
    'select': ['Selecione', 'Select', 'Seleccione', 'Sélectionner', 'Auswählen', 'Seleziona'],
    'realModeRequired': ['Obrigatório no modo real.', 'Required in real mode.', 'Obligatorio en modo real.', 'Obligatoire en mode réel.', 'Im Realmodus erforderlich.', 'Obbligatorio in modalità reale.'],
    'readingInterval': ['Intervalo de leitura', 'Reading interval', 'Intervalo de lectura', 'Intervalle de lecture', 'Leseintervall', 'Intervallo di lettura'],
    'operationalLimits': ['Limites operacionais e segurança', 'Operating limits and safety', 'Límites operativos y seguridad', 'Limites opérationnelles et sécurité', 'Betriebsgrenzen und Sicherheit', 'Limiti operativi e sicurezza'],
    'preventiveCycles': ['Ciclos para manutenção preventiva', 'Cycles until preventive maintenance', 'Ciclos para mantenimiento preventivo', 'Cycles avant maintenance préventive', 'Zyklen bis zur vorbeugenden Wartung', 'Cicli alla manutenzione preventiva'],
    'preventive': ['Preventiva', 'Preventive', 'Preventiva', 'Préventive', 'Präventiv', 'Preventiva'],
    'corrective': ['Corretiva', 'Corrective', 'Correctiva', 'Corrective', 'Korrektiv', 'Correttiva'],
    'predictive': ['Preditiva', 'Predictive', 'Predictiva', 'Prédictive', 'Prädiktiv', 'Predittiva'],
    'inspection': ['Inspeção', 'Inspection', 'Inspección', 'Inspection', 'Inspektion', 'Ispezione'],
    'lubrication': ['Lubrificação', 'Lubrication', 'Lubricación', 'Lubrification', 'Schmierung', 'Lubrificazione'],
    'companyUpdated': ['Dados da empresa atualizados com sucesso.', 'Company details updated successfully.', 'Datos de la empresa actualizados correctamente.', 'Données de l’entreprise mises à jour.', 'Unternehmensdaten erfolgreich aktualisiert.', 'Dati aziendali aggiornati correttamente.'],
    'employeeCreated': ['Funcionário cadastrado. Agora vincule a biometria facial.', 'Employee registered. Now link facial biometrics.', 'Empleado registrado. Ahora vincule la biometría facial.', 'Employé enregistré. Associez maintenant la biométrie faciale.', 'Mitarbeiter registriert. Verknüpfen Sie nun die Gesichtsbiometrie.', 'Dipendente registrato. Ora collega la biometria facciale.'],
    'accessUpdated': ['Dados de acesso atualizados com segurança.', 'Access details updated securely.', 'Datos de acceso actualizados de forma segura.', 'Données d’accès mises à jour en toute sécurité.', 'Zugangsdaten sicher aktualisiert.', 'Dati di accesso aggiornati in sicurezza.'],
    'cannotDismissSelf': ['Você não pode demitir sua própria conta.', 'You cannot dismiss your own account.', 'No puede despedir su propia cuenta.', 'Vous ne pouvez pas licencier votre propre compte.', 'Sie können Ihr eigenes Konto nicht entlassen.', 'Non puoi licenziare il tuo account.'],
    'dismissEmployeeTitle': ['Demitir funcionário?', 'Dismiss employee?', '¿Despedir al empleado?', 'Licencier l’employé ?', 'Mitarbeiter entlassen?', 'Licenziare il dipendente?'],
    'dismissEmployeeMessage': ['O acesso de {name} será desativado e todas as faciais serão revogadas. O histórico será preservado.', '{name}’s access will be disabled and all face records revoked. History will be preserved.', 'El acceso de {name} será desactivado y todos los rostros serán revocados. El historial se conservará.', 'L’accès de {name} sera désactivé et tous les visages seront révoqués. L’historique sera conservé.', 'Der Zugriff von {name} wird deaktiviert und alle Gesichtsdaten werden widerrufen. Der Verlauf bleibt erhalten.', 'L’accesso di {name} verrà disattivato e tutti i volti revocati. La cronologia sarà conservata.'],
    'employeeDismissed': ['Funcionário demitido. Acesso e biometria revogados.', 'Employee dismissed. Access and biometrics revoked.', 'Empleado despedido. Acceso y biometría revocados.', 'Employé licencié. Accès et biométrie révoqués.', 'Mitarbeiter entlassen. Zugriff und Biometrie widerrufen.', 'Dipendente licenziato. Accesso e biometria revocati.'],
    'noFaceProfile': ['Nenhuma facial cadastrada neste perfil.', 'No face registered for this profile.', 'No hay ningún rostro registrado en este perfil.', 'Aucun visage enregistré pour ce profil.', 'Für dieses Profil ist kein Gesicht registriert.', 'Nessun volto registrato per questo profilo.'],
    'primaryFace': ['Facial principal', 'Primary face', 'Rostro principal', 'Visage principal', 'Primäres Gesicht', 'Volto principale'],
    'removeFace': ['Remover facial', 'Remove face', 'Eliminar rostro', 'Supprimer le visage', 'Gesicht entfernen', 'Rimuovi volto'],
    'removeFaceTitle': ['Remover facial?', 'Remove face?', '¿Eliminar rostro?', 'Supprimer le visage ?', 'Gesicht entfernen?', 'Rimuovere il volto?'],
    'removeFaceMessage': ['O funcionário não poderá entrar por reconhecimento facial até realizar novo cadastro.', 'The employee will not be able to sign in with face recognition until registering again.', 'El empleado no podrá acceder por reconocimiento facial hasta registrarse nuevamente.', 'L’employé ne pourra plus se connecter par reconnaissance faciale avant un nouvel enregistrement.', 'Der Mitarbeiter kann sich erst nach erneuter Registrierung wieder per Gesichtserkennung anmelden.', 'Il dipendente non potrà accedere con il riconoscimento facciale fino a una nuova registrazione.'],
    'faceRemoved': ['Facial removida com sucesso.', 'Face removed successfully.', 'Rostro eliminado correctamente.', 'Visage supprimé avec succès.', 'Gesicht erfolgreich entfernt.', 'Volto rimosso correttamente.'],
    'removeMachineTitle': ['Remover máquina?', 'Remove machine?', '¿Eliminar máquina?', 'Supprimer la machine ?', 'Maschine entfernen?', 'Rimuovere la macchina?'],
    'removeMachineMessage': ['{name} será desativada. Telemetria, manutenções e auditoria serão preservadas.', '{name} will be disabled. Telemetry, maintenance and audit history will be preserved.', '{name} será desactivada. Se conservarán la telemetría, el mantenimiento y la auditoría.', '{name} sera désactivée. La télémétrie, la maintenance et l’audit seront conservés.', '{name} wird deaktiviert. Telemetrie, Wartung und Prüfverlauf bleiben erhalten.', '{name} verrà disattivata. Telemetria, manutenzione e audit saranno conservati.'],
    'newKey': ['Nova chave', 'New key', 'Nueva clave', 'Nouvelle clé', 'Neuer Schlüssel', 'Nuova chiave'],
    'generateNewKey': ['Gerar nova chave', 'Generate new key', 'Generar nueva clave', 'Générer une nouvelle clé', 'Neuen Schlüssel erzeugen', 'Genera nuova chiave'],
    'generateNewKeyTitle': ['Gerar nova chave?', 'Generate a new key?', '¿Generar una nueva clave?', 'Générer une nouvelle clé ?', 'Neuen Schlüssel erzeugen?', 'Generare una nuova chiave?'],
    'deviceKey': ['Chave do equipamento', 'Equipment key', 'Clave del equipo', 'Clé de l’équipement', 'Anlagenschlüssel', 'Chiave apparecchiatura'],
    'understood': ['Entendi', 'Got it', 'Entendido', 'Compris', 'Verstanden', 'Ho capito'],
    'code': ['Código', 'Code', 'Código', 'Code', 'Code', 'Codice'],
    'load': ['Carga', 'Load', 'Carga', 'Charge', 'Last', 'Carico'],
    'quickRegistration': ['Cadastro rápido e organizado', 'Quick, organized registration', 'Registro rápido y organizado', 'Enregistrement rapide et organisé', 'Schnelle, strukturierte Registrierung', 'Registrazione rapida e organizzata'],
    'quickRegistrationCaption': ['Os quatro campos essenciais são suficientes. Os demais podem ser preenchidos agora ou editados depois.', 'The four essential fields are enough to get started. The others can be completed now or edited later.', 'Los cuatro campos esenciales son suficientes. Los demás pueden completarse ahora o editarse después.', 'Les quatre champs essentiels suffisent. Les autres peuvent être remplis maintenant ou modifiés plus tard.', 'Die vier Pflichtfelder genügen. Die übrigen können jetzt oder später ausgefüllt werden.', 'I quattro campi essenziali sono sufficienti. Gli altri possono essere compilati ora o modificati dopo.'],
    'robotTemplateQuestion': ['Vai cadastrar um braço robótico?', 'Registering a robotic arm?', '¿Va a registrar un brazo robótico?', 'Vous enregistrez un bras robotisé ?', 'Registrieren Sie einen Roboterarm?', 'Vuoi registrare un braccio robotico?'],
    'useTemplate': ['Usar modelo', 'Use template', 'Usar modelo', 'Utiliser le modèle', 'Vorlage verwenden', 'Usa modello'],
    'equipmentIdentification': ['Identificação do equipamento', 'Equipment identification', 'Identificación del equipo', 'Identification de l’équipement', 'Anlagenidentifikation', 'Identificazione apparecchiatura'],
    'essentialPanelData': ['Dados essenciais usados nos painéis e relatórios.', 'Essential data used in dashboards and reports.', 'Datos esenciales utilizados en paneles e informes.', 'Données essentielles utilisées dans les tableaux de bord et rapports.', 'Wesentliche Daten für Dashboards und Berichte.', 'Dati essenziali usati nei pannelli e nei report.'],
    'additionalDetails': ['Detalhes adicionais', 'Additional details', 'Detalles adicionales', 'Détails supplémentaires', 'Weitere Details', 'Dettagli aggiuntivi'],
    'hideDetails': ['Ocultar detalhes', 'Hide details', 'Ocultar detalles', 'Masquer les détails', 'Details ausblenden', 'Nascondi dettagli'],
    'simulationCaption': ['Validação sem máquina conectada', 'Validation without a connected machine', 'Validación sin máquina conectada', 'Validation sans machine connectée', 'Prüfung ohne angeschlossene Maschine', 'Validazione senza macchina collegata'],
    'realTelemetryCaption': ['Telemetria do controlador', 'Controller telemetry', 'Telemetría del controlador', 'Télémétrie du contrôleur', 'Controller-Telemetrie', 'Telemetria del controller'],
    'simulationGenerated': ['O SteelControl gera dados para demonstração.', 'SteelControl generates demonstration data.', 'SteelControl genera datos de demostración.', 'SteelControl génère des données de démonstration.', 'SteelControl erzeugt Demonstrationsdaten.', 'SteelControl genera dati dimostrativi.'],
    'realStaysOffline': ['A máquina permanecerá offline até receber telemetria real.', 'The machine will remain offline until real telemetry is received.', 'La máquina permanecerá sin conexión hasta recibir telemetría real.', 'La machine restera hors ligne jusqu’à réception de la télémétrie réelle.', 'Die Maschine bleibt offline, bis echte Telemetrie empfangen wird.', 'La macchina resterà offline finché non riceverà telemetria reale.'],
    'communicationCaption': ['Opcional para simulação; necessária no equipamento real.', 'Optional for simulation; required for real equipment.', 'Opcional para simulación; necesaria para el equipo real.', 'Facultative en simulation ; requise pour l’équipement réel.', 'Für Simulation optional; für reale Anlagen erforderlich.', 'Opzionale per la simulazione; necessaria per l’apparecchiatura reale.'],
    'advancedNetwork': ['Configuração avançada de rede', 'Advanced network settings', 'Configuración avanzada de red', 'Configuration réseau avancée', 'Erweiterte Netzwerkeinstellungen', 'Configurazione di rete avanzata'],
    'hideAdvancedNetwork': ['Ocultar configuração avançada', 'Hide advanced settings', 'Ocultar configuración avanzada', 'Masquer la configuration avancée', 'Erweiterte Einstellungen ausblenden', 'Nascondi configurazione avanzata'],
    'recommendedLimits': ['Usar limites recomendados', 'Use recommended limits', 'Usar límites recomendados', 'Utiliser les limites recommandées', 'Empfohlene Grenzwerte verwenden', 'Usa limiti consigliati'],
    'customizeLimits': ['Personalizar limites', 'Customize limits', 'Personalizar límites', 'Personnaliser les limites', 'Grenzwerte anpassen', 'Personalizza limiti'],
    'recommendedValues': ['Valores recomendados já vêm preenchidos.', 'Recommended values are prefilled.', 'Los valores recomendados ya están completados.', 'Les valeurs recommandées sont préremplies.', 'Empfohlene Werte sind vorausgefüllt.', 'I valori consigliati sono precompilati.'],
    'roboticArm': ['Braço robótico', 'Robotic arm', 'Brazo robótico', 'Bras robotisé', 'Roboterarm', 'Braccio robotico'],
    'industrialRobot': ['Robô industrial', 'Industrial robot', 'Robot industrial', 'Robot industriel', 'Industrieroboter', 'Robot industriale'],
    'conveyor': ['Esteira industrial', 'Industrial conveyor', 'Cinta industrial', 'Convoyeur industriel', 'Industrieförderband', 'Nastro trasportatore'],
    'press': ['Prensa', 'Press', 'Prensa', 'Presse', 'Presse', 'Pressa'],
    'lathe': ['Torno', 'Lathe', 'Torno', 'Tour', 'Drehmaschine', 'Tornio'],
    'welding': ['Solda', 'Welding', 'Soldadura', 'Soudage', 'Schweißen', 'Saldatura'],
    'cutting': ['Corte', 'Cutting', 'Corte', 'Découpe', 'Schneiden', 'Taglio'],
    'packaging': ['Embalagem', 'Packaging', 'Embalaje', 'Emballage', 'Verpackung', 'Imballaggio'],
    'printer3d': ['Impressora 3D', '3D printer', 'Impresora 3D', 'Imprimante 3D', '3D-Drucker', 'Stampante 3D'],
    'other': ['Outro', 'Other', 'Otro', 'Autre', 'Andere', 'Altro'],
    'robotController': ['Controlador robótico', 'Robot controller', 'Controlador robótico', 'Contrôleur robotique', 'Robotersteuerung', 'Controller robotico'],
    'industrialGateway': ['Gateway industrial', 'Industrial gateway', 'Gateway industrial', 'Passerelle industrielle', 'Industrie-Gateway', 'Gateway industriale'],
    'gatewayMode': ['Modo do gateway', 'Gateway mode', 'Modo del gateway', 'Mode de la passerelle', 'Gateway-Modus', 'Modalità gateway'],
    'serialPort': ['Porta serial', 'Serial port', 'Puerto serie', 'Port série', 'Serieller Port', 'Porta seriale'],
    'preparePhysicalControl': ['Preparar controle físico', 'Prepare physical control', 'Preparar control físico', 'Préparer le contrôle physique', 'Physische Steuerung vorbereiten', 'Prepara controllo fisico'],
    'physicalControlCaption': ['O gateway continua protegido até a liberação consciente.', 'The gateway remains protected until explicit release.', 'El gateway permanece protegido hasta la liberación explícita.', 'La passerelle reste protégée jusqu’à une autorisation explicite.', 'Das Gateway bleibt bis zur ausdrücklichen Freigabe geschützt.', 'Il gateway resta protetto fino all’autorizzazione esplicita.'],
    'port': ['Porta', 'Port', 'Puerto', 'Port', 'Port', 'Porta'],
    'endpointPath': ['Endpoint / caminho', 'Endpoint / path', 'Endpoint / ruta', 'Point d’accès / chemin', 'Endpunkt / Pfad', 'Endpoint / percorso'],
    'mqttTopic': ['Tópico MQTT', 'MQTT topic', 'Tema MQTT', 'Sujet MQTT', 'MQTT-Thema', 'Topic MQTT'],
    'temperatureWarning': ['Temperatura de atenção', 'Temperature warning', 'Temperatura de atención', 'Alerte de température', 'Temperaturwarnung', 'Avviso temperatura'],
    'criticalTemperature': ['Temperatura crítica', 'Critical temperature', 'Temperatura crítica', 'Température critique', 'Kritische Temperatur', 'Temperatura critica'],
    'loadWarning': ['Carga de atenção (%)', 'Load warning (%)', 'Carga de atención (%)', 'Alerte de charge (%)', 'Lastwarnung (%)', 'Avviso carico (%)'],
    'criticalLoad': ['Carga crítica (%)', 'Critical load (%)', 'Carga crítica (%)', 'Charge critique (%)', 'Kritische Last (%)', 'Carico critico (%)'],
    'vibrationWarning': ['Vibração de atenção', 'Vibration warning', 'Vibración de atención', 'Alerte de vibration', 'Vibrationswarnung', 'Avviso vibrazione'],
    'criticalVibration': ['Vibração crítica', 'Critical vibration', 'Vibración crítica', 'Vibration critique', 'Kritische Vibration', 'Vibrazione critica'],
    'selectRealController': ['Selecione o controlador do equipamento real.', 'Select the controller for the real equipment.', 'Seleccione el controlador del equipo real.', 'Sélectionnez le contrôleur de l’équipement réel.', 'Wählen Sie den Controller der realen Anlage.', 'Seleziona il controller dell’apparecchiatura reale.'],
    'reviewLimits': ['Revise os limites informados.', 'Review the entered limits.', 'Revise los límites ingresados.', 'Vérifiez les limites saisies.', 'Prüfen Sie die eingegebenen Grenzwerte.', 'Controlla i limiti inseriti.'],
    'endEffectorPosition': ['Posição do efetuador', 'End-effector position', 'Posición del efector', 'Position de l’effecteur', 'Position des Endeffektors', 'Posizione dell’effettore'],
    'jointAngles': ['Ângulos das juntas', 'Joint angles', 'Ángulos de las articulaciones', 'Angles des articulations', 'Gelenkwinkel', 'Angoli dei giunti'],
    'supervisedControl': ['Controle supervisionado', 'Supervised control', 'Control supervisado', 'Contrôle supervisé', 'Überwachte Steuerung', 'Controllo supervisionato'],
    'secureQueueCaption': ['Os comandos passam pela fila segura do mesmo backend do desktop.', 'Commands pass through the same secure backend queue as the desktop.', 'Los comandos pasan por la misma cola segura del backend de escritorio.', 'Les commandes passent par la même file sécurisée que sur ordinateur.', 'Befehle laufen über dieselbe sichere Backend-Warteschlange wie am Desktop.', 'I comandi passano dalla stessa coda sicura del backend desktop.'],
    'stop': ['PARAR', 'STOP', 'DETENER', 'ARRÊTER', 'STOPP', 'ARRESTA'],
    'clearAlarms': ['Limpar alarmes', 'Clear alarms', 'Borrar alarmas', 'Effacer les alarmes', 'Alarme löschen', 'Cancella allarmi'],
    'openGripper': ['Abrir garra', 'Open gripper', 'Abrir pinza', 'Ouvrir la pince', 'Greifer öffnen', 'Apri pinza'],
    'closeGripper': ['Fechar garra', 'Close gripper', 'Cerrar pinza', 'Fermer la pince', 'Greifer schließen', 'Chiudi pinza'],
    'ptpMovement': ['Movimento cartesiano PTP', 'Cartesian PTP movement', 'Movimiento cartesiano PTP', 'Mouvement cartésien PTP', 'Kartesische PTP-Bewegung', 'Movimento cartesiano PTP'],
    'protectedMovement': ['MOVIMENTO PROTEGIDO', 'PROTECTED MOVEMENT', 'MOVIMIENTO PROTEGIDO', 'MOUVEMENT PROTÉGÉ', 'GESCHÜTZTE BEWEGUNG', 'MOVIMENTO PROTETTO'],
    'safetyValidationCaption': ['As faixas de segurança são validadas novamente pelo backend antes de chegar ao robô.', 'Safety ranges are validated again by the backend before reaching the robot.', 'Los rangos de seguridad son validados nuevamente por el backend antes de llegar al robot.', 'Les plages de sécurité sont à nouveau validées par le backend avant d’atteindre le robot.', 'Sicherheitsbereiche werden im Backend erneut geprüft, bevor sie den Roboter erreichen.', 'Gli intervalli di sicurezza vengono convalidati di nuovo dal backend prima di raggiungere il robot.'],
    'speed': ['Velocidade', 'Speed', 'Velocidad', 'Vitesse', 'Geschwindigkeit', 'Velocità'],
    'sending': ['Enviando...', 'Sending...', 'Enviando...', 'Envoi...', 'Wird gesendet...', 'Invio...'],
    'sendPtp': ['Enviar PTP', 'Send PTP', 'Enviar PTP', 'Envoyer PTP', 'PTP senden', 'Invia PTP'],
    'ptpFieldsRequired': ['Informe X, Y, Z e R antes de enviar o movimento.', 'Enter X, Y, Z and R before sending the movement.', 'Ingrese X, Y, Z y R antes de enviar el movimiento.', 'Saisissez X, Y, Z et R avant d’envoyer le mouvement.', 'Geben Sie X, Y, Z und R ein, bevor Sie die Bewegung senden.', 'Inserisci X, Y, Z e R prima di inviare il movimento.'],
    'ptpSent': ['Movimento PTP enviado para a fila segura.', 'PTP movement sent to the secure queue.', 'Movimiento PTP enviado a la cola segura.', 'Mouvement PTP envoyé à la file sécurisée.', 'PTP-Bewegung an die sichere Warteschlange gesendet.', 'Movimento PTP inviato alla coda sicura.'],
    'cameraUnavailable': ['Câmera indisponível', 'Camera unavailable', 'Cámara no disponible', 'Caméra indisponible', 'Kamera nicht verfügbar', 'Fotocamera non disponibile'],
    'cameraPermission': ['Autorize o acesso à câmera nas configurações do tablet.', 'Allow camera access in the tablet settings.', 'Autorice el acceso a la cámara en la configuración de la tableta.', 'Autorisez l’accès à la caméra dans les paramètres de la tablette.', 'Erlauben Sie den Kamerazugriff in den Tablet-Einstellungen.', 'Consenti l’accesso alla fotocamera nelle impostazioni del tablet.'],
    'faceValidationFailed': ['Não foi possível concluir a validação facial. Tente novamente.', 'Face validation could not be completed. Try again.', 'No se pudo completar la validación facial. Inténtelo de nuevo.', 'La validation faciale n’a pas pu être effectuée. Réessayez.', 'Die Gesichtsprüfung konnte nicht abgeschlossen werden. Versuchen Sie es erneut.', 'Impossibile completare la verifica facciale. Riprova.'],
    'adjustPosition': ['Ajuste a posição e tente novamente.', 'Adjust your position and try again.', 'Ajuste la posición e inténtelo de nuevo.', 'Ajustez votre position et réessayez.', 'Passen Sie Ihre Position an und versuchen Sie es erneut.', 'Regola la posizione e riprova.'],
    'qualityConfirmed': ['Qualidade confirmada', 'Quality confirmed', 'Calidad confirmada', 'Qualité confirmée', 'Qualität bestätigt', 'Qualità confermata'],
    'protectingBiometrics': ['Protegendo sua biometria no SteelControl...', 'Protecting your biometrics in SteelControl...', 'Protegiendo su biometría en SteelControl...', 'Protection de votre biométrie dans SteelControl...', 'Ihre Biometrie wird in SteelControl geschützt...', 'Protezione della biometria in SteelControl...'],
    'biometricsRegistered': ['Biometria cadastrada', 'Biometrics registered', 'Biometría registrada', 'Biométrie enregistrée', 'Biometrie registriert', 'Biometria registrata'],
    'biometricsLinkedOnce': ['Seu rosto foi vinculado uma única vez ao seu perfil.', 'Your face was linked once to your profile.', 'Su rostro se vinculó una sola vez a su perfil.', 'Votre visage a été associé une seule fois à votre profil.', 'Ihr Gesicht wurde einmalig mit Ihrem Profil verknüpft.', 'Il tuo volto è stato collegato una sola volta al profilo.'],
    'firstPosition': ['Primeira posição', 'First position', 'Primera posición', 'Première position', 'Erste Position', 'Prima posizione'],
    'returnCenter': ['Retorne ao centro', 'Return to center', 'Vuelva al centro', 'Revenez au centre', 'Zur Mitte zurückkehren', 'Torna al centro'],
    'lookAgain': ['Olhe novamente para a câmera.', 'Look at the camera again.', 'Mire de nuevo a la cámara.', 'Regardez à nouveau la caméra.', 'Schauen Sie erneut in die Kamera.', 'Guarda di nuovo la fotocamera.'],
    'verifyingIdentity': ['Verificando identidade', 'Verifying identity', 'Verificando identidad', 'Vérification de l’identité', 'Identität wird geprüft', 'Verifica identità'],
    'confirmingAccess': ['Aguarde enquanto confirmamos seu acesso.', 'Please wait while we confirm your access.', 'Espere mientras confirmamos su acceso.', 'Veuillez patienter pendant la confirmation de votre accès.', 'Bitte warten Sie, während wir Ihren Zugriff bestätigen.', 'Attendi mentre confermiamo il tuo accesso.'],
    'welcomeEnvironment': ['Bem-vindo ao seu ambiente SteelControl.', 'Welcome to your SteelControl workspace.', 'Bienvenido a su entorno SteelControl.', 'Bienvenue dans votre environnement SteelControl.', 'Willkommen in Ihrem SteelControl-Arbeitsbereich.', 'Benvenuto nel tuo ambiente SteelControl.'],
    'couldNotValidate': ['Não foi possível validar', 'Validation failed', 'No se pudo validar', 'Validation impossible', 'Validierung fehlgeschlagen', 'Validazione non riuscita'],
    'producedParts': ['peças produzidas', 'parts produced', 'piezas producidas', 'pièces produites', 'produzierte Teile', 'pezzi prodotti'],
    'robotCellPanel': ['PAINEL CÉLULA ROBÓTICA', 'ROBOT CELL DASHBOARD', 'PANEL DE CÉLULA ROBÓTICA', 'TABLEAU DE BORD CELLULE ROBOTISÉE', 'ROBOTERZELLEN-DASHBOARD', 'PANNELLO CELLA ROBOTICA'],
    'machineExclusivePanel': ['PAINEL EXCLUSIVO DA MÁQUINA', 'DEDICATED MACHINE DASHBOARD', 'PANEL EXCLUSIVO DE LA MÁQUINA', 'TABLEAU DE BORD DÉDIÉ À LA MACHINE', 'MASCHINEN-DASHBOARD', 'PANNELLO DEDICATO ALLA MACCHINA'],
    'waitingTelemetry': ['Aguardando telemetria', 'Waiting for telemetry', 'Esperando telemetría', 'En attente de télémétrie', 'Warten auf Telemetrie', 'In attesa della telemetria'],
    'normal': ['Normal', 'Normal', 'Normal', 'Normal', 'Normal', 'Normale'],
    'heating': ['Aquecimento', 'Heating', 'Calentamiento', 'Échauffement', 'Erwärmung', 'Riscaldamento'],
    'critical': ['Crítico', 'Critical', 'Crítico', 'Critique', 'Kritisch', 'Critico'],
    'normalize': ['Normalizar', 'Normalize', 'Normalizar', 'Normaliser', 'Normalisieren', 'Normalizza'],
    'esp32Activity': ['Atividade do ESP32', 'ESP32 activity', 'Actividad del ESP32', 'Activité de l’ESP32', 'ESP32-Aktivität', 'Attività ESP32'],
    'dobotOperations': ['Operações do Dobot', 'Dobot operations', 'Operaciones del Dobot', 'Opérations du Dobot', 'Dobot-Vorgänge', 'Operazioni Dobot'],
    'plcProduction': ['Produção do PLC', 'PLC production', 'Producción del PLC', 'Production de l’automate', 'SPS-Produktion', 'Produzione PLC'],
    'scanTime': ['Tempo de scan', 'Scan time', 'Tiempo de escaneo', 'Temps de cycle', 'Scanzeit', 'Tempo di scansione'],
    'machinedParts': ['Peças usinadas', 'Machined parts', 'Piezas mecanizadas', 'Pièces usinées', 'Bearbeitete Teile', 'Pezzi lavorati'],
    'spindleSpeed': ['Rotação do spindle', 'Spindle speed', 'Velocidad del husillo', 'Vitesse de broche', 'Spindeldrehzahl', 'Velocità mandrino'],
    'robotCycles': ['Ciclos robóticos', 'Robot cycles', 'Ciclos robóticos', 'Cycles robotiques', 'Roboterzyklen', 'Cicli robotici'],
    'gatewayActivity': ['Atividade do gateway', 'Gateway activity', 'Actividad del gateway', 'Activité de la passerelle', 'Gateway-Aktivität', 'Attività gateway'],
    'onlineDevices': ['Dispositivos online', 'Online devices', 'Dispositivos en línea', 'Appareils en ligne', 'Online-Geräte', 'Dispositivi online'],
    'movements': ['Movimentos', 'Movements', 'Movimientos', 'Mouvements', 'Bewegungen', 'Movimenti'],
    'safeQueue': ['Fila segura', 'Secure queue', 'Cola segura', 'File sécurisée', 'Sichere Warteschlange', 'Coda sicura'],
    'process': ['Processo', 'Process', 'Proceso', 'Processus', 'Prozess', 'Processo'],
    'devices': ['Dispositivos', 'Devices', 'Dispositivos', 'Appareils', 'Geräte', 'Dispositivi'],
    'protocols': ['Protocolos', 'Protocols', 'Protocolos', 'Protocoles', 'Protokolle', 'Protocolli'],
    'traffic': ['Tráfego', 'Traffic', 'Tráfico', 'Trafic', 'Datenverkehr', 'Traffico'],
    'telemetry': ['Telemetria', 'Telemetry', 'Telemetría', 'Télémétrie', 'Telemetrie', 'Telemetria'],
    'sensors': ['Sensores', 'Sensors', 'Sensores', 'Capteurs', 'Sensoren', 'Sensori'],
    'endEffector': ['Efetuador', 'End effector', 'Efector', 'Effecteur', 'Endeffektor', 'Effettore'],
    'registers': ['Registradores', 'Registers', 'Registros', 'Registres', 'Register', 'Registri'],
    'feed': ['Avanço', 'Feed', 'Avance', 'Avance', 'Vorschub', 'Avanzamento'],
    'program': ['Programa', 'Program', 'Programa', 'Programme', 'Programm', 'Programma'],
    'axes': ['Eixos', 'Axes', 'Ejes', 'Axes', 'Achsen', 'Assi'],
    'tool': ['Ferramenta', 'Tool', 'Herramienta', 'Outil', 'Werkzeug', 'Utensile'],
    'safety': ['Segurança', 'Safety', 'Seguridad', 'Sécurité', 'Sicherheit', 'Sicurezza'],
    'machineCreated': ['Máquina cadastrada com sucesso.', 'Machine registered successfully.', 'Máquina registrada correctamente.', 'Machine enregistrée avec succès.', 'Maschine erfolgreich registriert.', 'Macchina registrata correttamente.'],
    'machineUpdated': ['Máquina atualizada com sucesso.', 'Machine updated successfully.', 'Máquina actualizada correctamente.', 'Machine mise à jour avec succès.', 'Maschine erfolgreich aktualisiert.', 'Macchina aggiornata correttamente.'],
    'machineDisabled': ['Máquina desativada e histórico preservado.', 'Machine disabled and history preserved.', 'Máquina desactivada e historial conservado.', 'Machine désactivée et historique conservé.', 'Maschine deaktiviert und Verlauf erhalten.', 'Macchina disattivata e cronologia conservata.'],
    'faceAlreadyRegistered': ['Este perfil já possui uma facial. Remova a atual antes de cadastrar outra.', 'This profile already has a registered face. Remove it before registering another.', 'Este perfil ya tiene un rostro registrado. Elimínelo antes de registrar otro.', 'Ce profil possède déjà un visage. Supprimez-le avant d’en enregistrer un autre.', 'Dieses Profil hat bereits ein registriertes Gesicht. Entfernen Sie es vor einer neuen Registrierung.', 'Questo profilo ha già un volto registrato. Rimuovilo prima di registrarne un altro.'],
    'faceLinked': ['Facial vinculada ao perfil de {name}.', 'Face linked to {name}’s profile.', 'Rostro vinculado al perfil de {name}.', 'Visage associé au profil de {name}.', 'Gesicht mit dem Profil von {name} verknüpft.', 'Volto collegato al profilo di {name}.'],
    'commandSent': ['Comando {command} enviado para a fila.', 'Command {command} sent to the queue.', 'Comando {command} enviado a la cola.', 'Commande {command} envoyée à la file.', 'Befehl {command} an die Warteschlange gesendet.', 'Comando {command} inviato alla coda.'],
    'roleAdministrator': ['Administrador', 'Administrator', 'Administrador', 'Administrateur', 'Administrator', 'Amministratore'],
    'roleSupervisor': ['Supervisor', 'Supervisor', 'Supervisor', 'Superviseur', 'Vorgesetzter', 'Supervisore'],
    'roleTechnician': ['Técnico', 'Technician', 'Técnico', 'Technicien', 'Techniker', 'Tecnico'],
    'roleOperator': ['Operador', 'Operator', 'Operador', 'Opérateur', 'Bediener', 'Operatore'],
    'roleVisitor': ['Visitante', 'Visitor', 'Visitante', 'Visiteur', 'Besucher', 'Visitatore'],
    'networkUnavailable': ['Não foi possível conectar ao SteelControl. Verifique a rede do tablet.', 'Could not connect to SteelControl. Check the tablet network.', 'No se pudo conectar a SteelControl. Verifique la red de la tableta.', 'Impossible de se connecter à SteelControl. Vérifiez le réseau de la tablette.', 'Verbindung zu SteelControl fehlgeschlagen. Prüfen Sie das Tablet-Netzwerk.', 'Impossibile connettersi a SteelControl. Controlla la rete del tablet.'],
    'requestTimeout': ['O SteelControl demorou para responder. Tente novamente.', 'SteelControl took too long to respond. Try again.', 'SteelControl tardó demasiado en responder. Inténtelo de nuevo.', 'SteelControl a mis trop de temps à répondre. Réessayez.', 'SteelControl hat zu lange für die Antwort benötigt. Versuchen Sie es erneut.', 'SteelControl ha impiegato troppo tempo a rispondere. Riprova.'],
    'connectionInterrupted': ['A comunicação com o SteelControl foi interrompida.', 'Communication with SteelControl was interrupted.', 'La comunicación con SteelControl fue interrumpida.', 'La communication avec SteelControl a été interrompue.', 'Die Kommunikation mit SteelControl wurde unterbrochen.', 'La comunicazione con SteelControl è stata interrotta.'],
    'invalidServerResponse': ['O servidor retornou uma resposta inválida.', 'The server returned an invalid response.', 'El servidor devolvió una respuesta no válida.', 'Le serveur a renvoyé une réponse invalide.', 'Der Server hat eine ungültige Antwort geliefert.', 'Il server ha restituito una risposta non valida.'],
    'operationFailed': ['Não foi possível concluir a operação.', 'The operation could not be completed.', 'No se pudo completar la operación.', 'L’opération n’a pas pu être effectuée.', 'Der Vorgang konnte nicht abgeschlossen werden.', 'Impossibile completare l’operazione.'],
    'invalidSession': ['A autenticação não retornou uma sessão válida.', 'Authentication did not return a valid session.', 'La autenticación no devolvió una sesión válida.', 'L’authentification n’a pas renvoyé de session valide.', 'Die Authentifizierung hat keine gültige Sitzung zurückgegeben.', 'L’autenticazione non ha restituito una sessione valida.'],
    'waitingOperatorRelease': ['Aguardando liberação do operador', 'Waiting for operator release', 'Esperando liberación del operador', 'En attente de l’autorisation de l’opérateur', 'Warten auf Bedienerfreigabe', 'In attesa dell’autorizzazione dell’operatore'],
    'preventiveRequired': ['Manutenção preventiva necessária', 'Preventive maintenance required', 'Mantenimiento preventivo necesario', 'Maintenance préventive requise', 'Vorbeugende Wartung erforderlich', 'Manutenzione preventiva necessaria'],
    'preventiveRegistered': ['Preventiva registrada', 'Preventive maintenance registered', 'Mantenimiento preventivo registrado', 'Maintenance préventive enregistrée', 'Vorbeugende Wartung erfasst', 'Manutenzione preventiva registrata'],
    'noRecord': ['Sem registro', 'No record', 'Sin registro', 'Aucun enregistrement', 'Kein Eintrag', 'Nessun dato'],
    'audit': ["Auditoria", "Audit", "Auditoría", "Audit", "Audit", "Audit"],
    'auditCaption': ["Rastreabilidade completa de ações, acessos e alterações do sistema.", "Complete traceability of system actions, access and changes.", "Trazabilidad completa de acciones, accesos y cambios del sistema.", "Traçabilité complète des actions, accès et modifications du système.", "Vollständige Nachverfolgbarkeit von Aktionen, Zugriffen und Änderungen.", "Tracciabilità completa di azioni, accessi e modifiche del sistema."],
    'auditAdminOnly': ["A auditoria completa é restrita a administradores.", "Full audit access is restricted to administrators.", "La auditoría completa está restringida a administradores.", "L’audit complet est réservé aux administrateurs.", "Der vollständige Audit ist Administratoren vorbehalten.", "L’audit completo è riservato agli amministratori."],
    'auditLoaded': ["Eventos carregados", "Loaded events", "Eventos cargados", "Événements chargés", "Geladene Ereignisse", "Eventi caricati"],
    'auditFiltered': ["Resultado filtrado", "Filtered result", "Resultado filtrado", "Résultat filtré", "Gefiltertes Ergebnis", "Risultato filtrato"],
    'auditToday': ["Eventos hoje", "Events today", "Eventos hoy", "Événements aujourd’hui", "Ereignisse heute", "Eventi oggi"],
    'auditActors': ["Responsáveis", "Actors", "Responsables", "Responsables", "Akteure", "Responsabili"],
    'auditFilters': ["Filtros de auditoria", "Audit filters", "Filtros de auditoría", "Filtres d’audit", "Audit-Filter", "Filtri audit"],
    'auditSearch': ["Buscar por ação, entidade, usuário ou detalhe", "Search by action, entity, user or detail", "Buscar por acción, entidad, usuario o detalle", "Rechercher par action, entité, utilisateur ou détail", "Nach Aktion, Entität, Benutzer oder Detail suchen", "Cerca per azione, entità, utente o dettaglio"],
    'auditAction': ["Ação", "Action", "Acción", "Action", "Aktion", "Azione"],
    'auditEntity': ["Entidade", "Entity", "Entidad", "Entité", "Entität", "Entità"],
    'auditActor': ["Responsável", "Actor", "Responsable", "Responsable", "Akteur", "Responsabile"],
    'auditFrom': ["De", "From", "Desde", "Du", "Von", "Da"],
    'auditTo': ["Até", "To", "Hasta", "Au", "Bis", "A"],
    'auditNoResults': ["Nenhum evento corresponde aos filtros selecionados.", "No events match the selected filters.", "Ningún evento coincide con los filtros seleccionados.", "Aucun événement ne correspond aux filtres sélectionnés.", "Keine Ereignisse entsprechen den gewählten Filtern.", "Nessun evento corrisponde ai filtri selezionati."],
    'auditHistoryCount': ["Histórico • {count} eventos", "History • {count} events", "Historial • {count} eventos", "Historique • {count} événements", "Verlauf • {count} Ereignisse", "Cronologia • {count} eventi"],
    'auditNewestFirst': ["Mais recentes primeiro", "Newest first", "Más recientes primero", "Plus récents en premier", "Neueste zuerst", "Più recenti prima"],
    'auditNoDetails': ["Este evento não possui detalhes adicionais.", "This event has no additional details.", "Este evento no tiene detalles adicionales.", "Cet événement ne contient aucun détail supplémentaire.", "Dieses Ereignis enthält keine weiteren Details.", "Questo evento non contiene dettagli aggiuntivi."],
    'auditCreate': ["Criar", "Create", "Crear", "Créer", "Erstellen", "Crea"],
    'auditUpdate': ["Atualizar", "Update", "Actualizar", "Mettre à jour", "Aktualisieren", "Aggiorna"],
    'auditDisable': ["Desativar", "Disable", "Desactivar", "Désactiver", "Deaktivieren", "Disattiva"],
    'auditRemove': ["Remover", "Remove", "Eliminar", "Supprimer", "Entfernen", "Rimuovi"],
    'auditUpdateLogo': ["Atualizar logo", "Update logo", "Actualizar logo", "Mettre à jour le logo", "Logo aktualisieren", "Aggiorna logo"],
    'auditRemoveLogo': ["Remover logo", "Remove logo", "Eliminar logo", "Supprimer le logo", "Logo entfernen", "Rimuovi logo"],
    'auditLogin': ["Login", "Login", "Inicio de sesión", "Connexion", "Anmeldung", "Accesso"],
    'auditFaceLogin': ["Login facial", "Face login", "Inicio facial", "Connexion faciale", "Gesichtsanmeldung", "Accesso facciale"],
    'auditFaceRegister': ["Cadastrar facial", "Register face", "Registrar rostro", "Enregistrer le visage", "Gesicht registrieren", "Registra volto"],
    'auditFaceRemove': ["Remover facial", "Remove face", "Eliminar rostro", "Supprimer le visage", "Gesicht entfernen", "Rimuovi volto"],
    'auditSimulation': ["Simulação", "Simulation", "Simulación", "Simulation", "Simulation", "Simulazione"],
    'auditCommand': ["Comando enviado", "Command sent", "Comando enviado", "Commande envoyée", "Befehl gesendet", "Comando inviato"],
    'auditSafetyRelease': ["Liberar segurança", "Release safety", "Liberar seguridad", "Libérer la sécurité", "Sicherheit freigeben", "Rilascia sicurezza"],
    'auditCompany': ["Empresa", "Company", "Empresa", "Entreprise", "Unternehmen", "Azienda"],
    'auditUser': ["Usuário", "User", "Usuario", "Utilisateur", "Benutzer", "Utente"],
    'auditMachine': ["Máquina", "Machine", "Máquina", "Machine", "Maschine", "Macchina"],
    'auditMaintenance': ["Manutenção", "Maintenance", "Mantenimiento", "Maintenance", "Wartung", "Manutenzione"],
    'auditFace': ["Facial", "Face", "Rostro", "Visage", "Gesicht", "Volto"],
    'auditAuthentication': ["Autenticação", "Authentication", "Autenticación", "Authentification", "Authentifizierung", "Autenticazione"],
    'auditCommandEntity': ["Comando", "Command", "Comando", "Commande", "Befehl", "Comando"],
    'changeLogo': ["Alterar logo", "Change logo", "Cambiar logo", "Changer le logo", "Logo ändern", "Cambia logo"],
    'removeLogo': ["Remover logo", "Remove logo", "Eliminar logo", "Supprimer le logo", "Logo entfernen", "Rimuovi logo"],
    'invalidLogoFormat': ["Use uma imagem PNG, JPG, JPEG ou WEBP.", "Use a PNG, JPG, JPEG or WEBP image.", "Use una imagen PNG, JPG, JPEG o WEBP.", "Utilisez une image PNG, JPG, JPEG ou WEBP.", "Verwenden Sie ein PNG-, JPG-, JPEG- oder WEBP-Bild.", "Usa un’immagine PNG, JPG, JPEG o WEBP."],
    'logoUpdated': ["Logo atualizada com sucesso.", "Logo updated successfully.", "Logo actualizada correctamente.", "Logo mis à jour avec succès.", "Logo erfolgreich aktualisiert.", "Logo aggiornato correttamente."],
    'logoRemoved': ["Logo removida com sucesso.", "Logo removed successfully.", "Logo eliminada correctamente.", "Logo supprimé avec succès.", "Logo erfolgreich entfernt.", "Logo rimosso correttamente."],
    'logoFormatHint': ["PNG, JPG ou WEBP • recomendado até 1800 px", "PNG, JPG or WEBP • up to 1800 px recommended", "PNG, JPG o WEBP • recomendado hasta 1800 px", "PNG, JPG ou WEBP • jusqu’à 1800 px recommandé", "PNG, JPG oder WEBP • bis 1800 px empfohlen", "PNG, JPG o WEBP • consigliato fino a 1800 px"],
    'removeLogoTitle': ["Remover logo da empresa?", "Remove company logo?", "¿Eliminar el logo de la empresa?", "Supprimer le logo de l’entreprise ?", "Firmenlogo entfernen?", "Rimuovere il logo aziendale?"],
    'removeLogoMessage': ["A logo personalizada será removida e o SteelControl voltará a usar a identidade padrão.", "The custom logo will be removed and SteelControl will use its default identity.", "El logo personalizado se eliminará y SteelControl volverá a usar la identidad predeterminada.", "Le logo personnalisé sera supprimé et SteelControl utilisera son identité par défaut.", "Das benutzerdefinierte Logo wird entfernt und SteelControl verwendet wieder die Standardidentität.", "Il logo personalizzato verrà rimosso e SteelControl userà nuovamente l’identità predefinita."],
    'refresh': ["Atualizar", "Refresh", "Actualizar", "Actualiser", "Aktualisieren", "Aggiorna"],
    'all': ["Todos", "All", "Todos", "Tous", "Alle", "Tutti"],
    'clearFilters': ["Limpar filtros", "Clear filters", "Limpiar filtros", "Effacer les filtres", "Filter löschen", "Cancella filtri"],
    'clearDates': ["Limpar datas", "Clear dates", "Limpiar fechas", "Effacer les dates", "Daten löschen", "Cancella date"],
    'system': ["Sistema", "System", "Sistema", "Système", "System", "Sistema"],
    'controllerDiagnostics': ["Diagnóstico do controlador", "Controller diagnostics", "Diagnóstico del controlador", "Diagnostic du contrôleur", "Controller-Diagnose", "Diagnostica del controller"],
    'controllerResourcesCaption': ["recursos e comunicação específicos do equipamento", "equipment-specific resources and communication", "recursos y comunicación específicos del equipo", "ressources et communication spécifiques à l’équipement", "gerätespezifische Ressourcen und Kommunikation", "risorse e comunicazione specifiche dell’apparecchiatura"],
    'refreshDiagnostics': ["Atualizar diagnóstico", "Refresh diagnostics", "Actualizar diagnóstico", "Actualiser le diagnostic", "Diagnose aktualisieren", "Aggiorna diagnostica"],
    'liveDiagnostics': ["Diagnóstico do backend", "Backend diagnostics", "Diagnóstico del backend", "Diagnostic du backend", "Backend-Diagnose", "Diagnostica backend"],
    'localDiagnostics': ["Dados locais de contingência", "Local fallback data", "Datos locales de respaldo", "Données locales de secours", "Lokale Ersatzdaten", "Dati locali di fallback"],
    'diagnosticsFallback': ["O diagnóstico remoto não respondeu; os indicadores locais continuam disponíveis.", "Remote diagnostics did not respond; local indicators remain available.", "El diagnóstico remoto no respondió; los indicadores locales siguen disponibles.", "Le diagnostic distant ne répond pas ; les indicateurs locaux restent disponibles.", "Die Ferndiagnose antwortet nicht; lokale Anzeigen bleiben verfügbar.", "La diagnostica remota non ha risposto; gli indicatori locali restano disponibili."],
    'extendedDiagnostics': ["Detalhes recebidos do controlador", "Controller details received", "Detalles recibidos del controlador", "Détails reçus du contrôleur", "Vom Controller empfangene Details", "Dettagli ricevuti dal controller"],
    'extendedDiagnosticsCaption': ["Campos adicionais retornados pela integração.", "Additional fields returned by the integration.", "Campos adicionales devueltos por la integración.", "Champs supplémentaires renvoyés par l’intégration.", "Zusätzliche von der Integration gelieferte Felder.", "Campi aggiuntivi restituiti dall’integrazione."],
    'yes': ["Sim", "Yes", "Sí", "Oui", "Ja", "Sì"],
    'no': ["Não", "No", "No", "Non", "Nein", "No"],
    'connection': ["Conexão", "Connection", "Conexión", "Connexion", "Verbindung", "Connessione"],
    'heartbeat': ["Heartbeat", "Heartbeat", "Heartbeat", "Heartbeat", "Heartbeat", "Heartbeat"],
    'latency': ["Latência", "Latency", "Latencia", "Latence", "Latenz", "Latenza"],
    'readInterval': ["Intervalo de leitura", "Read interval", "Intervalo de lectura", "Intervalle de lecture", "Leseintervall", "Intervallo di lettura"],
    'host': ["Host / IP", "Host / IP", "Host / IP", "Hôte / IP", "Host / IP", "Host / IP"],
    'baudRate': ["Baud rate", "Baud rate", "Baud rate", "Débit en bauds", "Baudrate", "Baud rate"],
    'alarms': ["Alarmes", "Alarms", "Alarmas", "Alarmes", "Alarme", "Allarmi"],
    'plcIo': ["Entradas / saídas (I/O)", "Inputs / outputs (I/O)", "Entradas / salidas (I/O)", "Entrées / sorties (I/O)", "Ein-/Ausgänge (I/O)", "Ingressi / uscite (I/O)"],
    'unitId': ["Unit ID", "Unit ID", "Unit ID", "Unit ID", "Unit ID", "Unit ID"],
    'machineLoad': ["Carga da máquina", "Machine load", "Carga de la máquina", "Charge machine", "Maschinenlast", "Carico macchina"],
    'cycleTime': ["Tempo de ciclo", "Cycle time", "Tiempo de ciclo", "Temps de cycle", "Zykluszeit", "Tempo ciclo"],
    'controllerState': ["Estado do controlador", "Controller state", "Estado del controlador", "État du contrôleur", "Controller-Status", "Stato del controller"],
    'endpoint': ["Endpoint", "Endpoint", "Endpoint", "Endpoint", "Endpoint", "Endpoint"],
    'wifiRssi': ["Wi-Fi / RSSI", "Wi-Fi / RSSI", "Wi-Fi / RSSI", "Wi-Fi / RSSI", "Wi-Fi / RSSI", "Wi-Fi / RSSI"],
    'spindle': ["Spindle", "Spindle", "Husillo", "Broche", "Spindel", "Mandrino"],
    'suctionOn': ["Ventosa ligada", "Suction ON", "Ventosa activada", "Ventouse activée", "Sauger EIN", "Ventosa attiva"],
    'suctionOff': ["Ventosa desligada", "Suction OFF", "Ventosa desactivada", "Ventouse désactivée", "Sauger AUS", "Ventosa disattiva"],
    'tabletEyeLevel': ["Mantenha o tablet na altura dos olhos.", "Keep the tablet at eye level.", "Mantenga la tableta a la altura de los ojos.", "Gardez la tablette à hauteur des yeux.", "Halten Sie das Tablet auf Augenhöhe.", "Tieni il tablet all’altezza degli occhi."],
    'keepFaceStill': ["Mantenha o rosto centralizado e imóvel.", "Keep your face centered and still.", "Mantenga el rostro centrado e inmóvil.", "Gardez votre visage centré et immobile.", "Halten Sie Ihr Gesicht zentriert und still.", "Mantieni il viso centrato e immobile."],
    'lookCameraSentence': ["Olhe diretamente para a câmera.", "Look directly at the camera.", "Mire directamente a la cámara.", "Regardez directement la caméra.", "Schauen Sie direkt in die Kamera.", "Guarda direttamente la fotocamera."],
    'turnHeadSlightly': ["Vire levemente a cabeça para um dos lados.", "Turn your head slightly to one side.", "Gire ligeramente la cabeza hacia un lado.", "Tournez légèrement la tête sur un côté.", "Drehen Sie den Kopf leicht zu einer Seite.", "Gira leggermente la testa da un lato."],
    'movementNotDetected': ["O movimento não foi identificado. Vire um pouco mais a cabeça.", "Movement was not detected. Turn your head a little more.", "No se detectó el movimiento. Gire un poco más la cabeza.", "Le mouvement n’a pas été détecté. Tournez un peu plus la tête.", "Die Bewegung wurde nicht erkannt. Drehen Sie den Kopf etwas weiter.", "Il movimento non è stato rilevato. Gira un po’ di più la testa."],
    'returnFront': ["Retorne à posição frontal.", "Return to the front-facing position.", "Vuelva a la posición frontal.", "Revenez en position de face.", "Kehren Sie in die Frontalposition zurück.", "Torna alla posizione frontale."],
    'validationUnable': ["Não foi possível validar", "Unable to validate", "No se pudo validar", "Validation impossible", "Validierung nicht möglich", "Impossibile convalidare"],
    'faceIdTitle': ["Face ID SteelControl", "SteelControl Face ID", "Face ID SteelControl", "Face ID SteelControl", "SteelControl Face ID", "Face ID SteelControl"],
    'dobotGateway': ["Gateway Dobot Magician", "Dobot Magician Gateway", "Gateway Dobot Magician", "Passerelle Dobot Magician", "Dobot-Magician-Gateway", "Gateway Dobot Magician"],
    'automationSector': ["Automação", "Automation", "Automatización", "Automatisation", "Automatisierung", "Automazione"],
    'robotTemplateDescription': ["Braço robótico utilizado para movimentação, posicionamento e automação de processos industriais.", "Robotic arm used for movement, positioning and automation of industrial processes.", "Brazo robótico utilizado para movimiento, posicionamiento y automatización de procesos industriales.", "Bras robotisé utilisé pour le mouvement, le positionnement et l’automatisation des processus industriels.", "Roboterarm für Bewegung, Positionierung und Automatisierung industrieller Prozesse.", "Braccio robotico utilizzato per movimentazione, posizionamento e automazione dei processi industriali."],
    'toDefine': ["A definir", "To be defined", "Por definir", "À définir", "Noch festzulegen", "Da definire"],
    'machineOn': ["Ligada", "On", "Encendida", "En marche", "Ein", "Accesa"],
    'machineOff': ["Desligada", "Off", "Apagada", "Arrêtée", "Aus", "Spenta"],
    'safetyStopStatus': ["Parada de segurança", "Safety stop", "Parada de seguridad", "Arrêt de sécurité", "Sicherheitsstopp", "Arresto di sicurezza"],
    'configuredStatus': ["Configurada", "Configured", "Configurada", "Configurée", "Konfiguriert", "Configurata"],
    'notConfiguredFeminine': ["Não configurada", "Not configured", "No configurada", "Non configurée", "Nicht konfiguriert", "Non configurata"],
    'waitingConnection': ["Aguardando conexão", "Waiting for connection", "Esperando conexión", "En attente de connexion", "Warten auf Verbindung", "In attesa di connessione"],
    'failureStatus': ["Falha", "Failure", "Fallo", "Défaillance", "Fehler", "Guasto"],
    'criticalFeminine': ["Crítica", "Critical", "Crítica", "Critique", "Kritisch", "Critica"],
    'atCycle': ['No ciclo', 'At cycle', 'En el ciclo', 'Au cycle', 'Bei Zyklus', 'Al ciclo'],
  };

  String get(String key) {
    final index = AppLanguage.values.indexOf(language);
    return _values[key]?[index] ?? key;
  }

  String translate(String portugueseText) {
    for (final entry in _values.entries) {
      if (entry.value.first == portugueseText) {
        return entry.value[AppLanguage.values.indexOf(language)];
      }
    }
    if (portugueseText.startsWith('No ciclo ')) {
      return '${get('atCycle')} ${portugueseText.substring('No ciclo '.length)}';
    }
    return portugueseText;
  }

  static AppStrings of(BuildContext context) {
    final scope = context.dependOnInheritedWidgetOfExactType<_StringsScope>();
    return AppStrings(scope?.language ?? AppLanguage.pt);
  }
}

class AppStringsScope extends StatelessWidget {
  const AppStringsScope({
    required this.language,
    required this.child,
    super.key,
  });

  final AppLanguage language;
  final Widget child;

  @override
  Widget build(BuildContext context) => _StringsScope(
        language: language,
        child: child,
      );
}

class _StringsScope extends InheritedWidget {
  const _StringsScope({required this.language, required super.child});

  final AppLanguage language;

  @override
  bool updateShouldNotify(_StringsScope oldWidget) => language != oldWidget.language;
}
